/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ChatRouteImport } from "./routes/chat";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiLoginRouteImport } from "./routes/api/login";
import { Route as ApiChatSessionRouteImport } from "./routes/api/chat.session";

const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: "/api/login",
  path: "/api/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiChatSessionRoute = ApiChatSessionRouteImport.update({
  id: "/api/chat/session",
  path: "/api/chat/session",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/chat": typeof ChatRoute;
  "/api/login": typeof ApiLoginRoute;
  "/api/chat/session": typeof ApiChatSessionRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/chat": typeof ChatRoute;
  "/api/login": typeof ApiLoginRoute;
  "/api/chat/session": typeof ApiChatSessionRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/chat": typeof ChatRoute;
  "/api/login": typeof ApiLoginRoute;
  "/api/chat/session": typeof ApiChatSessionRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/chat" | "/api/login" | "/api/chat/session";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/chat" | "/api/login" | "/api/chat/session";
  id: "__root__" | "/" | "/chat" | "/api/login" | "/api/chat/session";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChatRoute: typeof ChatRoute;
  ApiLoginRoute: typeof ApiLoginRoute;
  ApiChatSessionRoute: typeof ApiChatSessionRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/login": {
      id: "/api/login";
      path: "/api/login";
      fullPath: "/api/login";
      preLoaderRoute: typeof ApiLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/chat/session": {
      id: "/api/chat/session";
      path: "/api/chat/session";
      fullPath: "/api/chat/session";
      preLoaderRoute: typeof ApiChatSessionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiChatSessionRoute: ApiChatSessionRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
