// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"net/http"
)

type CreateDeploymentSecurityOption1 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (c *CreateDeploymentSecurityOption1) GetApikeyHeaderGramKey() string {
	if c == nil {
		return ""
	}
	return c.ApikeyHeaderGramKey
}

func (c *CreateDeploymentSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if c == nil {
		return ""
	}
	return c.ProjectSlugHeaderGramProject
}

// #region class-body-createdeploymentsecurityoption1
// #endregion class-body-createdeploymentsecurityoption1

type CreateDeploymentSecurityOption2 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (c *CreateDeploymentSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if c == nil {
		return ""
	}
	return c.ProjectSlugHeaderGramProject
}

func (c *CreateDeploymentSecurityOption2) GetSessionHeaderGramSession() string {
	if c == nil {
		return ""
	}
	return c.SessionHeaderGramSession
}

// #region class-body-createdeploymentsecurityoption2
// #endregion class-body-createdeploymentsecurityoption2

type CreateDeploymentSecurity struct {
	Option1 *CreateDeploymentSecurityOption1 `security:"option"`
	Option2 *CreateDeploymentSecurityOption2 `security:"option"`
}

func (c CreateDeploymentSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDeploymentSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateDeploymentSecurity) GetOption1() *CreateDeploymentSecurityOption1 {
	if c == nil {
		return nil
	}
	return c.Option1
}

func (c *CreateDeploymentSecurity) GetOption2() *CreateDeploymentSecurityOption2 {
	if c == nil {
		return nil
	}
	return c.Option2
}

type CreateDeploymentRequest struct {
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// project header
	GramProject *string `header:"style=simple,explode=false,name=Gram-Project"`
	// A unique identifier that will mitigate against duplicate deployments.
	IdempotencyKey string                             `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           shared.CreateDeploymentRequestBody `request:"mediaType=application/json"`
}

func (c *CreateDeploymentRequest) GetGramKey() *string {
	if c == nil {
		return nil
	}
	return c.GramKey
}

func (c *CreateDeploymentRequest) GetGramSession() *string {
	if c == nil {
		return nil
	}
	return c.GramSession
}

func (c *CreateDeploymentRequest) GetGramProject() *string {
	if c == nil {
		return nil
	}
	return c.GramProject
}

func (c *CreateDeploymentRequest) GetIdempotencyKey() string {
	if c == nil {
		return ""
	}
	return c.IdempotencyKey
}

func (c *CreateDeploymentRequest) GetBody() shared.CreateDeploymentRequestBody {
	if c == nil {
		return shared.CreateDeploymentRequestBody{}
	}
	return c.Body
}

type CreateDeploymentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	CreateDeploymentResult *shared.CreateDeploymentResult
}

func (c CreateDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateDeploymentResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateDeploymentResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateDeploymentResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateDeploymentResponse) GetCreateDeploymentResult() *shared.CreateDeploymentResult {
	if c == nil {
		return nil
	}
	return c.CreateDeploymentResult
}
