// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"net/http"
)

type EvolveDeploymentSecurityOption1 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (e *EvolveDeploymentSecurityOption1) GetApikeyHeaderGramKey() string {
	if e == nil {
		return ""
	}
	return e.ApikeyHeaderGramKey
}

func (e *EvolveDeploymentSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if e == nil {
		return ""
	}
	return e.ProjectSlugHeaderGramProject
}

// #region class-body-evolvedeploymentsecurityoption1
// #endregion class-body-evolvedeploymentsecurityoption1

type EvolveDeploymentSecurityOption2 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (e *EvolveDeploymentSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if e == nil {
		return ""
	}
	return e.ProjectSlugHeaderGramProject
}

func (e *EvolveDeploymentSecurityOption2) GetSessionHeaderGramSession() string {
	if e == nil {
		return ""
	}
	return e.SessionHeaderGramSession
}

// #region class-body-evolvedeploymentsecurityoption2
// #endregion class-body-evolvedeploymentsecurityoption2

type EvolveDeploymentSecurity struct {
	Option1 *EvolveDeploymentSecurityOption1 `security:"option"`
	Option2 *EvolveDeploymentSecurityOption2 `security:"option"`
}

func (e EvolveDeploymentSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvolveDeploymentSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvolveDeploymentSecurity) GetOption1() *EvolveDeploymentSecurityOption1 {
	if e == nil {
		return nil
	}
	return e.Option1
}

func (e *EvolveDeploymentSecurity) GetOption2() *EvolveDeploymentSecurityOption2 {
	if e == nil {
		return nil
	}
	return e.Option2
}

type EvolveDeploymentRequest struct {
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// project header
	GramProject *string           `header:"style=simple,explode=false,name=Gram-Project"`
	Body        shared.EvolveForm `request:"mediaType=application/json"`
}

func (e *EvolveDeploymentRequest) GetGramKey() *string {
	if e == nil {
		return nil
	}
	return e.GramKey
}

func (e *EvolveDeploymentRequest) GetGramSession() *string {
	if e == nil {
		return nil
	}
	return e.GramSession
}

func (e *EvolveDeploymentRequest) GetGramProject() *string {
	if e == nil {
		return nil
	}
	return e.GramProject
}

func (e *EvolveDeploymentRequest) GetBody() shared.EvolveForm {
	if e == nil {
		return shared.EvolveForm{}
	}
	return e.Body
}

type EvolveDeploymentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	EvolveResult *shared.EvolveResult
}

func (e EvolveDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvolveDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvolveDeploymentResponse) GetContentType() string {
	if e == nil {
		return ""
	}
	return e.ContentType
}

func (e *EvolveDeploymentResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *EvolveDeploymentResponse) GetRawResponse() *http.Response {
	if e == nil {
		return nil
	}
	return e.RawResponse
}

func (e *EvolveDeploymentResponse) GetEvolveResult() *shared.EvolveResult {
	if e == nil {
		return nil
	}
	return e.EvolveResult
}
