// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"net/http"
)

type GetActiveDeploymentSecurityOption1 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (g *GetActiveDeploymentSecurityOption1) GetApikeyHeaderGramKey() string {
	if g == nil {
		return ""
	}
	return g.ApikeyHeaderGramKey
}

func (g *GetActiveDeploymentSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if g == nil {
		return ""
	}
	return g.ProjectSlugHeaderGramProject
}

// #region class-body-getactivedeploymentsecurityoption1
// #endregion class-body-getactivedeploymentsecurityoption1

type GetActiveDeploymentSecurityOption2 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (g *GetActiveDeploymentSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if g == nil {
		return ""
	}
	return g.ProjectSlugHeaderGramProject
}

func (g *GetActiveDeploymentSecurityOption2) GetSessionHeaderGramSession() string {
	if g == nil {
		return ""
	}
	return g.SessionHeaderGramSession
}

// #region class-body-getactivedeploymentsecurityoption2
// #endregion class-body-getactivedeploymentsecurityoption2

type GetActiveDeploymentSecurity struct {
	Option1 *GetActiveDeploymentSecurityOption1 `security:"option"`
	Option2 *GetActiveDeploymentSecurityOption2 `security:"option"`
}

func (g GetActiveDeploymentSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetActiveDeploymentSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetActiveDeploymentSecurity) GetOption1() *GetActiveDeploymentSecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetActiveDeploymentSecurity) GetOption2() *GetActiveDeploymentSecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

type GetActiveDeploymentRequest struct {
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// project header
	GramProject *string `header:"style=simple,explode=false,name=Gram-Project"`
}

func (g *GetActiveDeploymentRequest) GetGramKey() *string {
	if g == nil {
		return nil
	}
	return g.GramKey
}

func (g *GetActiveDeploymentRequest) GetGramSession() *string {
	if g == nil {
		return nil
	}
	return g.GramSession
}

func (g *GetActiveDeploymentRequest) GetGramProject() *string {
	if g == nil {
		return nil
	}
	return g.GramProject
}

type GetActiveDeploymentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	GetActiveDeploymentResult *shared.GetActiveDeploymentResult
}

func (g GetActiveDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetActiveDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetActiveDeploymentResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetActiveDeploymentResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetActiveDeploymentResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetActiveDeploymentResponse) GetGetActiveDeploymentResult() *shared.GetActiveDeploymentResult {
	if g == nil {
		return nil
	}
	return g.GetActiveDeploymentResult
}
