// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"net/http"
)

type GetDeploymentSecurityOption1 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (g *GetDeploymentSecurityOption1) GetApikeyHeaderGramKey() string {
	if g == nil {
		return ""
	}
	return g.ApikeyHeaderGramKey
}

func (g *GetDeploymentSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if g == nil {
		return ""
	}
	return g.ProjectSlugHeaderGramProject
}

// #region class-body-getdeploymentsecurityoption1
// #endregion class-body-getdeploymentsecurityoption1

type GetDeploymentSecurityOption2 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (g *GetDeploymentSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if g == nil {
		return ""
	}
	return g.ProjectSlugHeaderGramProject
}

func (g *GetDeploymentSecurityOption2) GetSessionHeaderGramSession() string {
	if g == nil {
		return ""
	}
	return g.SessionHeaderGramSession
}

// #region class-body-getdeploymentsecurityoption2
// #endregion class-body-getdeploymentsecurityoption2

type GetDeploymentSecurity struct {
	Option1 *GetDeploymentSecurityOption1 `security:"option"`
	Option2 *GetDeploymentSecurityOption2 `security:"option"`
}

func (g GetDeploymentSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDeploymentSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetDeploymentSecurity) GetOption1() *GetDeploymentSecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetDeploymentSecurity) GetOption2() *GetDeploymentSecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

type GetDeploymentRequest struct {
	// The ID of the deployment
	ID string `queryParam:"style=form,explode=true,name=id"`
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// project header
	GramProject *string `header:"style=simple,explode=false,name=Gram-Project"`
}

func (g *GetDeploymentRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeploymentRequest) GetGramKey() *string {
	if g == nil {
		return nil
	}
	return g.GramKey
}

func (g *GetDeploymentRequest) GetGramSession() *string {
	if g == nil {
		return nil
	}
	return g.GramSession
}

func (g *GetDeploymentRequest) GetGramProject() *string {
	if g == nil {
		return nil
	}
	return g.GramProject
}

type GetDeploymentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	GetDeploymentResult *shared.GetDeploymentResult
}

func (g GetDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetDeploymentResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDeploymentResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDeploymentResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetDeploymentResponse) GetGetDeploymentResult() *shared.GetDeploymentResult {
	if g == nil {
		return nil
	}
	return g.GetDeploymentResult
}
