// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"net/http"
)

type GetLatestDeploymentSecurityOption1 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (g *GetLatestDeploymentSecurityOption1) GetApikeyHeaderGramKey() string {
	if g == nil {
		return ""
	}
	return g.ApikeyHeaderGramKey
}

func (g *GetLatestDeploymentSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if g == nil {
		return ""
	}
	return g.ProjectSlugHeaderGramProject
}

// #region class-body-getlatestdeploymentsecurityoption1
// #endregion class-body-getlatestdeploymentsecurityoption1

type GetLatestDeploymentSecurityOption2 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (g *GetLatestDeploymentSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if g == nil {
		return ""
	}
	return g.ProjectSlugHeaderGramProject
}

func (g *GetLatestDeploymentSecurityOption2) GetSessionHeaderGramSession() string {
	if g == nil {
		return ""
	}
	return g.SessionHeaderGramSession
}

// #region class-body-getlatestdeploymentsecurityoption2
// #endregion class-body-getlatestdeploymentsecurityoption2

type GetLatestDeploymentSecurity struct {
	Option1 *GetLatestDeploymentSecurityOption1 `security:"option"`
	Option2 *GetLatestDeploymentSecurityOption2 `security:"option"`
}

func (g GetLatestDeploymentSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetLatestDeploymentSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetLatestDeploymentSecurity) GetOption1() *GetLatestDeploymentSecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetLatestDeploymentSecurity) GetOption2() *GetLatestDeploymentSecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

type GetLatestDeploymentRequest struct {
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// project header
	GramProject *string `header:"style=simple,explode=false,name=Gram-Project"`
}

func (g *GetLatestDeploymentRequest) GetGramKey() *string {
	if g == nil {
		return nil
	}
	return g.GramKey
}

func (g *GetLatestDeploymentRequest) GetGramSession() *string {
	if g == nil {
		return nil
	}
	return g.GramSession
}

func (g *GetLatestDeploymentRequest) GetGramProject() *string {
	if g == nil {
		return nil
	}
	return g.GramProject
}

type GetLatestDeploymentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	GetLatestDeploymentResult *shared.GetLatestDeploymentResult
}

func (g GetLatestDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetLatestDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetLatestDeploymentResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetLatestDeploymentResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetLatestDeploymentResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetLatestDeploymentResponse) GetGetLatestDeploymentResult() *shared.GetLatestDeploymentResult {
	if g == nil {
		return nil
	}
	return g.GetLatestDeploymentResult
}
