// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"net/http"
)

type GetToolsetSecurityOption1 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (g *GetToolsetSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if g == nil {
		return ""
	}
	return g.ProjectSlugHeaderGramProject
}

func (g *GetToolsetSecurityOption1) GetSessionHeaderGramSession() string {
	if g == nil {
		return ""
	}
	return g.SessionHeaderGramSession
}

// #region class-body-gettoolsetsecurityoption1
// #endregion class-body-gettoolsetsecurityoption1

type GetToolsetSecurityOption2 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (g *GetToolsetSecurityOption2) GetApikeyHeaderGramKey() string {
	if g == nil {
		return ""
	}
	return g.ApikeyHeaderGramKey
}

func (g *GetToolsetSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if g == nil {
		return ""
	}
	return g.ProjectSlugHeaderGramProject
}

// #region class-body-gettoolsetsecurityoption2
// #endregion class-body-gettoolsetsecurityoption2

type GetToolsetSecurity struct {
	Option1 *GetToolsetSecurityOption1 `security:"option"`
	Option2 *GetToolsetSecurityOption2 `security:"option"`
}

func (g GetToolsetSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetToolsetSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetToolsetSecurity) GetOption1() *GetToolsetSecurityOption1 {
	if g == nil {
		return nil
	}
	return g.Option1
}

func (g *GetToolsetSecurity) GetOption2() *GetToolsetSecurityOption2 {
	if g == nil {
		return nil
	}
	return g.Option2
}

type GetToolsetRequest struct {
	// The slug of the toolset
	Slug string `queryParam:"style=form,explode=true,name=slug"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// project header
	GramProject *string `header:"style=simple,explode=false,name=Gram-Project"`
}

func (g *GetToolsetRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

func (g *GetToolsetRequest) GetGramSession() *string {
	if g == nil {
		return nil
	}
	return g.GramSession
}

func (g *GetToolsetRequest) GetGramKey() *string {
	if g == nil {
		return nil
	}
	return g.GramKey
}

func (g *GetToolsetRequest) GetGramProject() *string {
	if g == nil {
		return nil
	}
	return g.GramProject
}

type GetToolsetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	Toolset *shared.Toolset
}

func (g GetToolsetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetToolsetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetToolsetResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetToolsetResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetToolsetResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetToolsetResponse) GetToolset() *shared.Toolset {
	if g == nil {
		return nil
	}
	return g.Toolset
}
