// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"net/http"
)

type ListToolsetsSecurityOption1 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (l *ListToolsetsSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if l == nil {
		return ""
	}
	return l.ProjectSlugHeaderGramProject
}

func (l *ListToolsetsSecurityOption1) GetSessionHeaderGramSession() string {
	if l == nil {
		return ""
	}
	return l.SessionHeaderGramSession
}

// #region class-body-listtoolsetssecurityoption1
// #endregion class-body-listtoolsetssecurityoption1

type ListToolsetsSecurityOption2 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (l *ListToolsetsSecurityOption2) GetApikeyHeaderGramKey() string {
	if l == nil {
		return ""
	}
	return l.ApikeyHeaderGramKey
}

func (l *ListToolsetsSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if l == nil {
		return ""
	}
	return l.ProjectSlugHeaderGramProject
}

// #region class-body-listtoolsetssecurityoption2
// #endregion class-body-listtoolsetssecurityoption2

type ListToolsetsSecurity struct {
	Option1 *ListToolsetsSecurityOption1 `security:"option"`
	Option2 *ListToolsetsSecurityOption2 `security:"option"`
}

func (l ListToolsetsSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListToolsetsSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListToolsetsSecurity) GetOption1() *ListToolsetsSecurityOption1 {
	if l == nil {
		return nil
	}
	return l.Option1
}

func (l *ListToolsetsSecurity) GetOption2() *ListToolsetsSecurityOption2 {
	if l == nil {
		return nil
	}
	return l.Option2
}

type ListToolsetsRequest struct {
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// project header
	GramProject *string `header:"style=simple,explode=false,name=Gram-Project"`
}

func (l *ListToolsetsRequest) GetGramSession() *string {
	if l == nil {
		return nil
	}
	return l.GramSession
}

func (l *ListToolsetsRequest) GetGramKey() *string {
	if l == nil {
		return nil
	}
	return l.GramKey
}

func (l *ListToolsetsRequest) GetGramProject() *string {
	if l == nil {
		return nil
	}
	return l.GramProject
}

type ListToolsetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	ListToolsetsResult *shared.ListToolsetsResult
}

func (l ListToolsetsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListToolsetsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListToolsetsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListToolsetsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListToolsetsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListToolsetsResponse) GetListToolsetsResult() *shared.ListToolsetsResult {
	if l == nil {
		return nil
	}
	return l.ListToolsetsResult
}
