// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"net/http"
)

type RedeployDeploymentSecurityOption1 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (r *RedeployDeploymentSecurityOption1) GetApikeyHeaderGramKey() string {
	if r == nil {
		return ""
	}
	return r.ApikeyHeaderGramKey
}

func (r *RedeployDeploymentSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if r == nil {
		return ""
	}
	return r.ProjectSlugHeaderGramProject
}

// #region class-body-redeploydeploymentsecurityoption1
// #endregion class-body-redeploydeploymentsecurityoption1

type RedeployDeploymentSecurityOption2 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (r *RedeployDeploymentSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if r == nil {
		return ""
	}
	return r.ProjectSlugHeaderGramProject
}

func (r *RedeployDeploymentSecurityOption2) GetSessionHeaderGramSession() string {
	if r == nil {
		return ""
	}
	return r.SessionHeaderGramSession
}

// #region class-body-redeploydeploymentsecurityoption2
// #endregion class-body-redeploydeploymentsecurityoption2

type RedeployDeploymentSecurity struct {
	Option1 *RedeployDeploymentSecurityOption1 `security:"option"`
	Option2 *RedeployDeploymentSecurityOption2 `security:"option"`
}

func (r RedeployDeploymentSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RedeployDeploymentSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RedeployDeploymentSecurity) GetOption1() *RedeployDeploymentSecurityOption1 {
	if r == nil {
		return nil
	}
	return r.Option1
}

func (r *RedeployDeploymentSecurity) GetOption2() *RedeployDeploymentSecurityOption2 {
	if r == nil {
		return nil
	}
	return r.Option2
}

type RedeployDeploymentRequest struct {
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// project header
	GramProject *string                    `header:"style=simple,explode=false,name=Gram-Project"`
	Body        shared.RedeployRequestBody `request:"mediaType=application/json"`
}

func (r *RedeployDeploymentRequest) GetGramKey() *string {
	if r == nil {
		return nil
	}
	return r.GramKey
}

func (r *RedeployDeploymentRequest) GetGramSession() *string {
	if r == nil {
		return nil
	}
	return r.GramSession
}

func (r *RedeployDeploymentRequest) GetGramProject() *string {
	if r == nil {
		return nil
	}
	return r.GramProject
}

func (r *RedeployDeploymentRequest) GetBody() shared.RedeployRequestBody {
	if r == nil {
		return shared.RedeployRequestBody{}
	}
	return r.Body
}

type RedeployDeploymentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	RedeployResult *shared.RedeployResult
}

func (r RedeployDeploymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RedeployDeploymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RedeployDeploymentResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RedeployDeploymentResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RedeployDeploymentResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RedeployDeploymentResponse) GetRedeployResult() *shared.RedeployResult {
	if r == nil {
		return nil
	}
	return r.RedeployResult
}
