// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"net/http"
)

type UploadOpenAPIv3AssetSecurityOption1 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (u *UploadOpenAPIv3AssetSecurityOption1) GetApikeyHeaderGramKey() string {
	if u == nil {
		return ""
	}
	return u.ApikeyHeaderGramKey
}

func (u *UploadOpenAPIv3AssetSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if u == nil {
		return ""
	}
	return u.ProjectSlugHeaderGramProject
}

// #region class-body-uploadopenapiv3assetsecurityoption1
// #endregion class-body-uploadopenapiv3assetsecurityoption1

type UploadOpenAPIv3AssetSecurityOption2 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (u *UploadOpenAPIv3AssetSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if u == nil {
		return ""
	}
	return u.ProjectSlugHeaderGramProject
}

func (u *UploadOpenAPIv3AssetSecurityOption2) GetSessionHeaderGramSession() string {
	if u == nil {
		return ""
	}
	return u.SessionHeaderGramSession
}

// #region class-body-uploadopenapiv3assetsecurityoption2
// #endregion class-body-uploadopenapiv3assetsecurityoption2

type UploadOpenAPIv3AssetSecurity struct {
	Option1 *UploadOpenAPIv3AssetSecurityOption1 `security:"option"`
	Option2 *UploadOpenAPIv3AssetSecurityOption2 `security:"option"`
}

func (u UploadOpenAPIv3AssetSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadOpenAPIv3AssetSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadOpenAPIv3AssetSecurity) GetOption1() *UploadOpenAPIv3AssetSecurityOption1 {
	if u == nil {
		return nil
	}
	return u.Option1
}

func (u *UploadOpenAPIv3AssetSecurity) GetOption2() *UploadOpenAPIv3AssetSecurityOption2 {
	if u == nil {
		return nil
	}
	return u.Option2
}

// #region class-body-uploadopenapiv3assetsecurity
// #endregion class-body-uploadopenapiv3assetsecurity

type UploadOpenAPIv3AssetRequest struct {
	ContentLength int64 `header:"style=simple,explode=false,name=Content-Length"`
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// project header
	GramProject *string `header:"style=simple,explode=false,name=Gram-Project"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Body any `request:"mediaType=application/octet-stream"`
}

func (u *UploadOpenAPIv3AssetRequest) GetContentLength() int64 {
	if u == nil {
		return 0
	}
	return u.ContentLength
}

func (u *UploadOpenAPIv3AssetRequest) GetGramKey() *string {
	if u == nil {
		return nil
	}
	return u.GramKey
}

func (u *UploadOpenAPIv3AssetRequest) GetGramProject() *string {
	if u == nil {
		return nil
	}
	return u.GramProject
}

func (u *UploadOpenAPIv3AssetRequest) GetGramSession() *string {
	if u == nil {
		return nil
	}
	return u.GramSession
}

func (u *UploadOpenAPIv3AssetRequest) GetBody() any {
	if u == nil {
		return nil
	}
	return u.Body
}

// #region class-body-uploadopenapiv3assetrequest
// #endregion class-body-uploadopenapiv3assetrequest

type UploadOpenAPIv3AssetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	UploadOpenAPIv3Result *shared.UploadOpenAPIv3Result
}

func (u UploadOpenAPIv3AssetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadOpenAPIv3AssetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadOpenAPIv3AssetResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UploadOpenAPIv3AssetResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UploadOpenAPIv3AssetResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UploadOpenAPIv3AssetResponse) GetUploadOpenAPIv3Result() *shared.UploadOpenAPIv3Result {
	if u == nil {
		return nil
	}
	return u.UploadOpenAPIv3Result
}

// #region class-body-uploadopenapiv3assetresponse
// #endregion class-body-uploadopenapiv3assetresponse
