// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"net/http"
)

type UploadFunctionsSecurityOption1 struct {
	ApikeyHeaderGramKey          string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (u *UploadFunctionsSecurityOption1) GetApikeyHeaderGramKey() string {
	if u == nil {
		return ""
	}
	return u.ApikeyHeaderGramKey
}

func (u *UploadFunctionsSecurityOption1) GetProjectSlugHeaderGramProject() string {
	if u == nil {
		return ""
	}
	return u.ProjectSlugHeaderGramProject
}

// #region class-body-uploadfunctionssecurityoption1
// #endregion class-body-uploadfunctionssecurityoption1

type UploadFunctionsSecurityOption2 struct {
	ProjectSlugHeaderGramProject string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
	SessionHeaderGramSession     string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Session"`
}

func (u *UploadFunctionsSecurityOption2) GetProjectSlugHeaderGramProject() string {
	if u == nil {
		return ""
	}
	return u.ProjectSlugHeaderGramProject
}

func (u *UploadFunctionsSecurityOption2) GetSessionHeaderGramSession() string {
	if u == nil {
		return ""
	}
	return u.SessionHeaderGramSession
}

// #region class-body-uploadfunctionssecurityoption2
// #endregion class-body-uploadfunctionssecurityoption2

type UploadFunctionsSecurity struct {
	Option1 *UploadFunctionsSecurityOption1 `security:"option"`
	Option2 *UploadFunctionsSecurityOption2 `security:"option"`
}

func (u UploadFunctionsSecurity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadFunctionsSecurity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadFunctionsSecurity) GetOption1() *UploadFunctionsSecurityOption1 {
	if u == nil {
		return nil
	}
	return u.Option1
}

func (u *UploadFunctionsSecurity) GetOption2() *UploadFunctionsSecurityOption2 {
	if u == nil {
		return nil
	}
	return u.Option2
}

type UploadFunctionsRequest struct {
	ContentLength int64 `header:"style=simple,explode=false,name=Content-Length"`
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
	// project header
	GramProject *string `header:"style=simple,explode=false,name=Gram-Project"`
	// Session header
	GramSession *string `header:"style=simple,explode=false,name=Gram-Session"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Body any `request:"mediaType=application/octet-stream"`
}

func (u *UploadFunctionsRequest) GetContentLength() int64 {
	if u == nil {
		return 0
	}
	return u.ContentLength
}

func (u *UploadFunctionsRequest) GetGramKey() *string {
	if u == nil {
		return nil
	}
	return u.GramKey
}

func (u *UploadFunctionsRequest) GetGramProject() *string {
	if u == nil {
		return nil
	}
	return u.GramProject
}

func (u *UploadFunctionsRequest) GetGramSession() *string {
	if u == nil {
		return nil
	}
	return u.GramSession
}

func (u *UploadFunctionsRequest) GetBody() any {
	if u == nil {
		return nil
	}
	return u.Body
}

type UploadFunctionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	UploadFunctionsResult *shared.UploadFunctionsResult
}

func (u UploadFunctionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadFunctionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadFunctionsResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UploadFunctionsResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UploadFunctionsResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UploadFunctionsResponse) GetUploadFunctionsResult() *shared.UploadFunctionsResult {
	if u == nil {
		return nil
	}
	return u.UploadFunctionsResult
}
