// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/models/shared"
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"net/http"
)

type ValidateAPIKeySecurity struct {
	ApikeyHeaderGramKey string `security:"scheme,type=apiKey,subtype=header,name=Gram-Key"`
}

func (v *ValidateAPIKeySecurity) GetApikeyHeaderGramKey() string {
	if v == nil {
		return ""
	}
	return v.ApikeyHeaderGramKey
}

type ValidateAPIKeyRequest struct {
	// API Key header
	GramKey *string `header:"style=simple,explode=false,name=Gram-Key"`
}

func (v *ValidateAPIKeyRequest) GetGramKey() *string {
	if v == nil {
		return nil
	}
	return v.GramKey
}

type ValidateAPIKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK response.
	ValidateKeyResult *shared.ValidateKeyResult
}

func (v ValidateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ValidateAPIKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *ValidateAPIKeyResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *ValidateAPIKeyResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *ValidateAPIKeyResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *ValidateAPIKeyResponse) GetValidateKeyResult() *shared.ValidateKeyResult {
	if v == nil {
		return nil
	}
	return v.ValidateKeyResult
}
