// Reads the Vite single-file build output and emits a TS module that inlines
// it as a string literal. Mirrors the pizzaz example's build-inlined.ts: the
// gram function bundler sees plain string imports rather than needing asset
// plugins.

import { readFileSync, writeFileSync, mkdirSync, statSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const src = resolve(root, "dist-ui/index.html");
const dst = resolve(root, "src/inlined.ts");

const html = readFileSync(src, "utf8");
const bytes = statSync(src).size;

mkdirSync(dirname(dst), { recursive: true });
writeFileSync(
  dst,
  [
    "// AUTO-GENERATED by scripts/inline-html.mjs. Do not edit.",
    `export const HTML = ${JSON.stringify(html)};`,
    "",
  ].join("\n"),
);

console.log(`inlined ${bytes.toLocaleString()} bytes → ${dst}`);
