// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AddDeploymentPackageForm struct {
	// The name of the package.
	Name string `json:"name"`
	// The version of the package.
	Version *string `json:"version,omitzero"`
}

func (a *AddDeploymentPackageForm) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AddDeploymentPackageForm) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}
