// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
)

type AddExternalMCPForm struct {
	// The display name for the external MCP server.
	Name string `json:"name"`
	// The ID of the internal collection registry the server is from.
	OrganizationMcpCollectionRegistryID *string `json:"organization_mcp_collection_registry_id,omitzero"`
	// The ID of the external MCP registry the server is from.
	RegistryID *string `json:"registry_id,omitzero"`
	// The canonical server name used to look up the server in the registry (e.g., 'slack', 'ai.exa/exa').
	RegistryServerSpecifier string `json:"registry_server_specifier"`
	// URLs of the remotes to use for this MCP server. If not provided, the backend will auto-select based on transport type preference.
	SelectedRemotes []string `json:"selected_remotes,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
}

func (a AddExternalMCPForm) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddExternalMCPForm) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddExternalMCPForm) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AddExternalMCPForm) GetOrganizationMcpCollectionRegistryID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationMcpCollectionRegistryID
}

func (a *AddExternalMCPForm) GetRegistryID() *string {
	if a == nil {
		return nil
	}
	return a.RegistryID
}

func (a *AddExternalMCPForm) GetRegistryServerSpecifier() string {
	if a == nil {
		return ""
	}
	return a.RegistryServerSpecifier
}

func (a *AddExternalMCPForm) GetSelectedRemotes() []string {
	if a == nil {
		return nil
	}
	return a.SelectedRemotes
}

func (a *AddExternalMCPForm) GetSlug() string {
	if a == nil {
		return ""
	}
	return a.Slug
}
