// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AddFunctionsForm struct {
	// The ID of the functions file from the assets service.
	AssetID string `json:"asset_id"`
	// The amount of memory in MiB to allocate for the function (1 MiB = 1024 * 1024 bytes).
	MemoryMib *int64 `json:"memory_mib,omitzero"`
	// The functions file display name.
	Name string `json:"name"`
	// The runtime to use when executing functions. Allowed values are: nodejs:22, nodejs:24, python:3.12.
	Runtime string `json:"runtime"`
	// The number of instances to scale the function to.
	Scale *int64 `json:"scale,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
}

func (a *AddFunctionsForm) GetAssetID() string {
	if a == nil {
		return ""
	}
	return a.AssetID
}

func (a *AddFunctionsForm) GetMemoryMib() *int64 {
	if a == nil {
		return nil
	}
	return a.MemoryMib
}

func (a *AddFunctionsForm) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AddFunctionsForm) GetRuntime() string {
	if a == nil {
		return ""
	}
	return a.Runtime
}

func (a *AddFunctionsForm) GetScale() *int64 {
	if a == nil {
		return nil
	}
	return a.Scale
}

func (a *AddFunctionsForm) GetSlug() string {
	if a == nil {
		return ""
	}
	return a.Slug
}
