// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AddOpenAPIv3DeploymentAssetForm struct {
	// The ID of the uploaded asset.
	AssetID string `json:"asset_id"`
	// The name to give the document as it will be displayed in UIs.
	Name string `json:"name"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
}

func (a *AddOpenAPIv3DeploymentAssetForm) GetAssetID() string {
	if a == nil {
		return ""
	}
	return a.AssetID
}

func (a *AddOpenAPIv3DeploymentAssetForm) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AddOpenAPIv3DeploymentAssetForm) GetSlug() string {
	if a == nil {
		return ""
	}
	return a.Slug
}

// #region class-body-addopenapiv3deploymentassetform
// #endregion class-body-addopenapiv3deploymentassetform
