// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AddPackageForm struct {
	// The name of the package to add.
	Name string `json:"name"`
	// The version of the package to add. If omitted, the latest version will be used.
	Version *string `json:"version,omitzero"`
}

func (a *AddPackageForm) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AddPackageForm) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}
