// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"time"
)

type Kind string

const (
	KindOpenapiv3      Kind = "openapiv3"
	KindImage          Kind = "image"
	KindFunctions      Kind = "functions"
	KindChatAttachment Kind = "chat_attachment"
	KindUnknown        Kind = "unknown"
)

func (e Kind) ToPointer() *Kind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Kind) IsExact() bool {
	if e != nil {
		switch *e {
		case "openapiv3", "image", "functions", "chat_attachment", "unknown":
			return true
		}
	}
	return false
}

type Asset struct {
	// The content length of the asset
	ContentLength int64 `json:"content_length"`
	// The content type of the asset
	ContentType string `json:"content_type"`
	// The creation date of the asset.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the asset
	ID   string `json:"id"`
	Kind Kind   `json:"kind"`
	// The SHA256 hash of the asset
	Sha256 string `json:"sha256"`
	// The last update date of the asset.
	UpdatedAt time.Time `json:"updated_at"`
}

func (a Asset) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Asset) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Asset) GetContentLength() int64 {
	if a == nil {
		return 0
	}
	return a.ContentLength
}

func (a *Asset) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *Asset) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *Asset) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *Asset) GetKind() Kind {
	if a == nil {
		return Kind("")
	}
	return a.Kind
}

func (a *Asset) GetSha256() string {
	if a == nil {
		return ""
	}
	return a.Sha256
}

func (a *Asset) GetUpdatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.UpdatedAt
}
