// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CanonicalToolAttributes - The original details of a tool
type CanonicalToolAttributes struct {
	// Confirmation mode for the tool
	Confirm *string `json:"confirm,omitzero"`
	// Prompt for the confirmation
	ConfirmPrompt *string `json:"confirm_prompt,omitzero"`
	// Description of the tool
	Description string `json:"description"`
	// The name of the tool
	Name string `json:"name"`
	// Summarizer for the tool
	Summarizer *string `json:"summarizer,omitzero"`
	// The ID of the variation that was applied to the tool
	VariationID string `json:"variation_id"`
}

func (c *CanonicalToolAttributes) GetConfirm() *string {
	if c == nil {
		return nil
	}
	return c.Confirm
}

func (c *CanonicalToolAttributes) GetConfirmPrompt() *string {
	if c == nil {
		return nil
	}
	return c.ConfirmPrompt
}

func (c *CanonicalToolAttributes) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CanonicalToolAttributes) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CanonicalToolAttributes) GetSummarizer() *string {
	if c == nil {
		return nil
	}
	return c.Summarizer
}

func (c *CanonicalToolAttributes) GetVariationID() string {
	if c == nil {
		return ""
	}
	return c.VariationID
}
