// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
)

type CreateDeploymentResult struct {
	Deployment *Deployment `json:"deployment,omitzero"`
}

func (c CreateDeploymentResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDeploymentResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateDeploymentResult) GetDeployment() *Deployment {
	if c == nil {
		return nil
	}
	return c.Deployment
}
