// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
)

type CreateDeploymentRequestBody struct {
	// The external ID to refer to the deployment. This can be a git commit hash for example.
	ExternalID   *string              `json:"external_id,omitzero"`
	ExternalMcps []AddExternalMCPForm `json:"external_mcps,omitzero"`
	// The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
	ExternalURL *string            `json:"external_url,omitzero"`
	Functions   []AddFunctionsForm `json:"functions,omitzero"`
	// The github pull request that resulted in the deployment.
	GithubPr *string `json:"github_pr,omitzero"`
	// The github repository in the form of "owner/repo".
	GithubRepo *string `json:"github_repo,omitzero"`
	// The commit hash that triggered the deployment.
	GithubSha *string `json:"github_sha,omitzero"`
	// If true, the deployment will be created in non-blocking mode where the request will return immediately and the deployment will proceed asynchronously.
	NonBlocking     *bool                             `json:"non_blocking,omitzero"`
	Openapiv3Assets []AddOpenAPIv3DeploymentAssetForm `json:"openapiv3_assets,omitzero"`
	Packages        []AddDeploymentPackageForm        `json:"packages,omitzero"`
}

func (c CreateDeploymentRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDeploymentRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateDeploymentRequestBody) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CreateDeploymentRequestBody) GetExternalMcps() []AddExternalMCPForm {
	if c == nil {
		return nil
	}
	return c.ExternalMcps
}

func (c *CreateDeploymentRequestBody) GetExternalURL() *string {
	if c == nil {
		return nil
	}
	return c.ExternalURL
}

func (c *CreateDeploymentRequestBody) GetFunctions() []AddFunctionsForm {
	if c == nil {
		return nil
	}
	return c.Functions
}

func (c *CreateDeploymentRequestBody) GetGithubPr() *string {
	if c == nil {
		return nil
	}
	return c.GithubPr
}

func (c *CreateDeploymentRequestBody) GetGithubRepo() *string {
	if c == nil {
		return nil
	}
	return c.GithubRepo
}

func (c *CreateDeploymentRequestBody) GetGithubSha() *string {
	if c == nil {
		return nil
	}
	return c.GithubSha
}

func (c *CreateDeploymentRequestBody) GetNonBlocking() *bool {
	if c == nil {
		return nil
	}
	return c.NonBlocking
}

func (c *CreateDeploymentRequestBody) GetOpenapiv3Assets() []AddOpenAPIv3DeploymentAssetForm {
	if c == nil {
		return nil
	}
	return c.Openapiv3Assets
}

func (c *CreateDeploymentRequestBody) GetPackages() []AddDeploymentPackageForm {
	if c == nil {
		return nil
	}
	return c.Packages
}
