// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"time"
)

type Deployment struct {
	// The ID of the deployment that this deployment was cloned from.
	ClonedFrom *string `json:"cloned_from,omitzero"`
	// The creation date of the deployment.
	CreatedAt time.Time `json:"created_at"`
	// The external ID to refer to the deployment. This can be a git commit hash for example.
	ExternalID *string `json:"external_id,omitzero"`
	// The number of tools in the deployment generated from external MCP servers.
	ExternalMcpToolCount int64 `json:"external_mcp_tool_count"`
	// The external MCP servers that were deployed.
	ExternalMcps []DeploymentExternalMCP `json:"external_mcps,omitzero"`
	// The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
	ExternalURL *string `json:"external_url,omitzero"`
	// The IDs, as returned from the assets upload service, to uploaded OpenAPI 3.x documents whose operations will become tool definitions.
	FunctionsAssets []DeploymentFunctions `json:"functions_assets,omitzero"`
	// The number of tools in the deployment generated from Functions.
	FunctionsToolCount int64 `json:"functions_tool_count"`
	// The github pull request that resulted in the deployment.
	GithubPr *string `json:"github_pr,omitzero"`
	// The github repository in the form of "owner/repo".
	GithubRepo *string `json:"github_repo,omitzero"`
	// The commit hash that triggered the deployment.
	GithubSha *string `json:"github_sha,omitzero"`
	// The ID to of the deployment.
	ID string `json:"id"`
	// A unique identifier that will mitigate against duplicate deployments.
	IdempotencyKey *string `json:"idempotency_key,omitzero"`
	// The IDs, as returned from the assets upload service, to uploaded OpenAPI 3.x documents whose operations will become tool definitions.
	Openapiv3Assets []OpenAPIv3DeploymentAsset `json:"openapiv3_assets"`
	// The number of tools in the deployment generated from OpenAPI documents.
	Openapiv3ToolCount int64 `json:"openapiv3_tool_count"`
	// The ID of the organization that the deployment belongs to.
	OrganizationID string `json:"organization_id"`
	// The packages that were deployed.
	Packages []DeploymentPackage `json:"packages"`
	// The ID of the project that the deployment belongs to.
	ProjectID string `json:"project_id"`
	// The status of the deployment.
	Status string `json:"status"`
	// The ID of the user that created the deployment.
	UserID string `json:"user_id"`
}

func (d Deployment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Deployment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *Deployment) GetClonedFrom() *string {
	if d == nil {
		return nil
	}
	return d.ClonedFrom
}

func (d *Deployment) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *Deployment) GetExternalID() *string {
	if d == nil {
		return nil
	}
	return d.ExternalID
}

func (d *Deployment) GetExternalMcpToolCount() int64 {
	if d == nil {
		return 0
	}
	return d.ExternalMcpToolCount
}

func (d *Deployment) GetExternalMcps() []DeploymentExternalMCP {
	if d == nil {
		return nil
	}
	return d.ExternalMcps
}

func (d *Deployment) GetExternalURL() *string {
	if d == nil {
		return nil
	}
	return d.ExternalURL
}

func (d *Deployment) GetFunctionsAssets() []DeploymentFunctions {
	if d == nil {
		return nil
	}
	return d.FunctionsAssets
}

func (d *Deployment) GetFunctionsToolCount() int64 {
	if d == nil {
		return 0
	}
	return d.FunctionsToolCount
}

func (d *Deployment) GetGithubPr() *string {
	if d == nil {
		return nil
	}
	return d.GithubPr
}

func (d *Deployment) GetGithubRepo() *string {
	if d == nil {
		return nil
	}
	return d.GithubRepo
}

func (d *Deployment) GetGithubSha() *string {
	if d == nil {
		return nil
	}
	return d.GithubSha
}

func (d *Deployment) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *Deployment) GetIdempotencyKey() *string {
	if d == nil {
		return nil
	}
	return d.IdempotencyKey
}

func (d *Deployment) GetOpenapiv3Assets() []OpenAPIv3DeploymentAsset {
	if d == nil {
		return []OpenAPIv3DeploymentAsset{}
	}
	return d.Openapiv3Assets
}

func (d *Deployment) GetOpenapiv3ToolCount() int64 {
	if d == nil {
		return 0
	}
	return d.Openapiv3ToolCount
}

func (d *Deployment) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *Deployment) GetPackages() []DeploymentPackage {
	if d == nil {
		return []DeploymentPackage{}
	}
	return d.Packages
}

func (d *Deployment) GetProjectID() string {
	if d == nil {
		return ""
	}
	return d.ProjectID
}

func (d *Deployment) GetStatus() string {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *Deployment) GetUserID() string {
	if d == nil {
		return ""
	}
	return d.UserID
}
