// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DeploymentExternalMCP struct {
	// The ID of the deployment external MCP record.
	ID string `json:"id"`
	// The display name for the external MCP server.
	Name string `json:"name"`
	// The ID of the internal collection registry the server is from.
	OrganizationMcpCollectionRegistryID *string `json:"organization_mcp_collection_registry_id,omitzero"`
	// The ID of the external MCP registry the server is from.
	RegistryID *string `json:"registry_id,omitzero"`
	// The canonical server name used to look up the server in the registry.
	RegistryServerSpecifier string `json:"registry_server_specifier"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
}

func (d *DeploymentExternalMCP) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeploymentExternalMCP) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DeploymentExternalMCP) GetOrganizationMcpCollectionRegistryID() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationMcpCollectionRegistryID
}

func (d *DeploymentExternalMCP) GetRegistryID() *string {
	if d == nil {
		return nil
	}
	return d.RegistryID
}

func (d *DeploymentExternalMCP) GetRegistryServerSpecifier() string {
	if d == nil {
		return ""
	}
	return d.RegistryServerSpecifier
}

func (d *DeploymentExternalMCP) GetSlug() string {
	if d == nil {
		return ""
	}
	return d.Slug
}
