// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DeploymentPackage struct {
	// The ID of the deployment package.
	ID string `json:"id"`
	// The name of the package.
	Name string `json:"name"`
	// The version of the package.
	Version string `json:"version"`
}

func (d *DeploymentPackage) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeploymentPackage) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DeploymentPackage) GetVersion() string {
	if d == nil {
		return ""
	}
	return d.Version
}
