// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DeploymentFunctions struct {
	// The ID of the uploaded asset.
	AssetID string `json:"asset_id"`
	// The ID of the deployment asset.
	ID string `json:"id"`
	// The memory limit in MiB of function runner machines.
	MemoryMib *int `json:"memory_mib,omitzero"`
	// The name to give the document as it will be displayed in UIs.
	Name string `json:"name"`
	// The runtime to use when executing functions.
	Runtime string `json:"runtime"`
	// The number of instances to run for the function.
	Scale *int `json:"scale,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
}

func (d *DeploymentFunctions) GetAssetID() string {
	if d == nil {
		return ""
	}
	return d.AssetID
}

func (d *DeploymentFunctions) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeploymentFunctions) GetMemoryMib() *int {
	if d == nil {
		return nil
	}
	return d.MemoryMib
}

func (d *DeploymentFunctions) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DeploymentFunctions) GetRuntime() string {
	if d == nil {
		return ""
	}
	return d.Runtime
}

func (d *DeploymentFunctions) GetScale() *int {
	if d == nil {
		return nil
	}
	return d.Scale
}

func (d *DeploymentFunctions) GetSlug() string {
	if d == nil {
		return ""
	}
	return d.Slug
}
