// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
)

type EvolveForm struct {
	// The ID of the deployment to evolve. If omitted, the latest deployment will be used.
	DeploymentID *string `json:"deployment_id,omitzero"`
	// The external MCP servers, identified by slug, to exclude from the new deployment when cloning a previous deployment.
	ExcludeExternalMcps []string `json:"exclude_external_mcps,omitzero"`
	// The functions, identified by slug, to exclude from the new deployment when cloning a previous deployment.
	ExcludeFunctions []string `json:"exclude_functions,omitzero"`
	// The OpenAPI 3.x documents, identified by slug, to exclude from the new deployment when cloning a previous deployment.
	ExcludeOpenapiv3Assets []string `json:"exclude_openapiv3_assets,omitzero"`
	// The packages to exclude from the new deployment when cloning a previous deployment.
	ExcludePackages []string `json:"exclude_packages,omitzero"`
	// If true, the deployment will be created in non-blocking mode where the request will return immediately and the deployment will proceed asynchronously.
	NonBlocking *bool `json:"non_blocking,omitzero"`
	// The external MCP servers to upsert in the new deployment.
	UpsertExternalMcps []AddExternalMCPForm `json:"upsert_external_mcps,omitzero"`
	// The tool functions to upsert in the new deployment.
	UpsertFunctions []AddFunctionsForm `json:"upsert_functions,omitzero"`
	// The OpenAPI 3.x documents to upsert in the new deployment.
	UpsertOpenapiv3Assets []AddOpenAPIv3DeploymentAssetForm `json:"upsert_openapiv3_assets,omitzero"`
	// The packages to upsert in the new deployment.
	UpsertPackages []AddPackageForm `json:"upsert_packages,omitzero"`
}

func (e EvolveForm) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvolveForm) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvolveForm) GetDeploymentID() *string {
	if e == nil {
		return nil
	}
	return e.DeploymentID
}

func (e *EvolveForm) GetExcludeExternalMcps() []string {
	if e == nil {
		return nil
	}
	return e.ExcludeExternalMcps
}

func (e *EvolveForm) GetExcludeFunctions() []string {
	if e == nil {
		return nil
	}
	return e.ExcludeFunctions
}

func (e *EvolveForm) GetExcludeOpenapiv3Assets() []string {
	if e == nil {
		return nil
	}
	return e.ExcludeOpenapiv3Assets
}

func (e *EvolveForm) GetExcludePackages() []string {
	if e == nil {
		return nil
	}
	return e.ExcludePackages
}

func (e *EvolveForm) GetNonBlocking() *bool {
	if e == nil {
		return nil
	}
	return e.NonBlocking
}

func (e *EvolveForm) GetUpsertExternalMcps() []AddExternalMCPForm {
	if e == nil {
		return nil
	}
	return e.UpsertExternalMcps
}

func (e *EvolveForm) GetUpsertFunctions() []AddFunctionsForm {
	if e == nil {
		return nil
	}
	return e.UpsertFunctions
}

func (e *EvolveForm) GetUpsertOpenapiv3Assets() []AddOpenAPIv3DeploymentAssetForm {
	if e == nil {
		return nil
	}
	return e.UpsertOpenapiv3Assets
}

func (e *EvolveForm) GetUpsertPackages() []AddPackageForm {
	if e == nil {
		return nil
	}
	return e.UpsertPackages
}
