// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
)

type EvolveResult struct {
	Deployment *Deployment `json:"deployment,omitzero"`
}

func (e EvolveResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvolveResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvolveResult) GetDeployment() *Deployment {
	if e == nil {
		return nil
	}
	return e.Deployment
}
