// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ExternalMCPHeaderDefinition struct {
	// Description of the header
	Description *string `json:"description,omitzero"`
	// The actual HTTP header name to send (e.g., X-Api-Key)
	HeaderName string `json:"header_name"`
	// The prefixed environment variable name (e.g., SLACK_X_API_KEY)
	Name string `json:"name"`
	// Placeholder value for the header
	Placeholder *string `json:"placeholder,omitzero"`
	// Whether the header is required
	Required bool `json:"required"`
	// Whether the header value is secret
	Secret bool `json:"secret"`
}

func (e *ExternalMCPHeaderDefinition) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *ExternalMCPHeaderDefinition) GetHeaderName() string {
	if e == nil {
		return ""
	}
	return e.HeaderName
}

func (e *ExternalMCPHeaderDefinition) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *ExternalMCPHeaderDefinition) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *ExternalMCPHeaderDefinition) GetRequired() bool {
	if e == nil {
		return false
	}
	return e.Required
}

func (e *ExternalMCPHeaderDefinition) GetSecret() bool {
	if e == nil {
		return false
	}
	return e.Secret
}
