// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"time"
)

type ExternalOAuthServer struct {
	// When the external OAuth server was created.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the external OAuth server
	ID string `json:"id"`
	// The metadata for the external OAuth server
	Metadata any `json:"metadata"`
	// The project ID this external OAuth server belongs to
	ProjectID string `json:"project_id"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
	// When the external OAuth server was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (e ExternalOAuthServer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExternalOAuthServer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExternalOAuthServer) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *ExternalOAuthServer) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExternalOAuthServer) GetMetadata() any {
	if e == nil {
		return nil
	}
	return e.Metadata
}

func (e *ExternalOAuthServer) GetProjectID() string {
	if e == nil {
		return ""
	}
	return e.ProjectID
}

func (e *ExternalOAuthServer) GetSlug() string {
	if e == nil {
		return ""
	}
	return e.Slug
}

func (e *ExternalOAuthServer) GetUpdatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.UpdatedAt
}
