// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"time"
)

// TransportType - The transport type used to connect to the MCP server
type TransportType string

const (
	TransportTypeStreamableHTTP TransportType = "streamable-http"
	TransportTypeSse            TransportType = "sse"
)

func (e TransportType) ToPointer() *TransportType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransportType) IsExact() bool {
	if e != nil {
		switch *e {
		case "streamable-http", "sse":
			return true
		}
	}
	return false
}

// ExternalMCPToolDefinition - A proxy tool that references an external MCP server
type ExternalMCPToolDefinition struct {
	// Tool annotations providing behavioral hints about the tool
	Annotations *ToolAnnotations `json:"annotations,omitzero"`
	// The original details of a tool
	Canonical *CanonicalToolAttributes `json:"canonical,omitzero"`
	// The canonical name of the tool. Will be the same as the name if there is no variation.
	CanonicalName string `json:"canonical_name"`
	// Confirmation mode for the tool
	Confirm *string `json:"confirm,omitzero"`
	// Prompt for the confirmation
	ConfirmPrompt *string `json:"confirm_prompt,omitzero"`
	// The creation date of the tool.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the deployments_external_mcps record
	DeploymentExternalMcpID string `json:"deployment_external_mcp_id"`
	// The ID of the deployment
	DeploymentID string `json:"deployment_id"`
	// Description of the tool
	Description string `json:"description"`
	// The ID of the tool
	ID string `json:"id"`
	// The name of the tool
	Name string `json:"name"`
	// The OAuth authorization endpoint URL
	OauthAuthorizationEndpoint *string `json:"oauth_authorization_endpoint,omitzero"`
	// The OAuth dynamic client registration endpoint URL
	OauthRegistrationEndpoint *string `json:"oauth_registration_endpoint,omitzero"`
	// The OAuth scopes supported by the server
	OauthScopesSupported []string `json:"oauth_scopes_supported,omitzero"`
	// The OAuth token endpoint URL
	OauthTokenEndpoint *string `json:"oauth_token_endpoint,omitzero"`
	// OAuth version: '2.1' (MCP OAuth), '2.0' (legacy), or 'none'
	OauthVersion string `json:"oauth_version"`
	// The ID of the project
	ProjectID string `json:"project_id"`
	// The ID of the MCP registry
	RegistryID string `json:"registry_id"`
	// The name of the external MCP server (e.g., exa)
	RegistryServerName string `json:"registry_server_name"`
	// The specifier of the external MCP server (e.g., 'io.modelcontextprotocol.anonymous/exa')
	RegistrySpecifier string `json:"registry_specifier"`
	// The URL to connect to the MCP server
	RemoteURL string `json:"remote_url"`
	// Whether the external MCP server requires OAuth authentication
	RequiresOauth bool `json:"requires_oauth"`
	// JSON schema for the request
	Schema string `json:"schema"`
	// Version of the schema
	SchemaVersion *string `json:"schema_version,omitzero"`
	// The slug used for tool prefixing (e.g., github)
	Slug string `json:"slug"`
	// Summarizer for the tool
	Summarizer *string `json:"summarizer,omitzero"`
	// The URN of this tool
	ToolUrn string `json:"tool_urn"`
	// The transport type used to connect to the MCP server
	TransportType TransportType `json:"transport_type"`
	// Whether or not the tool is a proxy tool
	Type *string `json:"type,omitzero"`
	// The last update date of the tool.
	UpdatedAt time.Time      `json:"updated_at"`
	Variation *ToolVariation `json:"variation,omitzero"`
}

func (e ExternalMCPToolDefinition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExternalMCPToolDefinition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExternalMCPToolDefinition) GetAnnotations() *ToolAnnotations {
	if e == nil {
		return nil
	}
	return e.Annotations
}

func (e *ExternalMCPToolDefinition) GetCanonical() *CanonicalToolAttributes {
	if e == nil {
		return nil
	}
	return e.Canonical
}

func (e *ExternalMCPToolDefinition) GetCanonicalName() string {
	if e == nil {
		return ""
	}
	return e.CanonicalName
}

func (e *ExternalMCPToolDefinition) GetConfirm() *string {
	if e == nil {
		return nil
	}
	return e.Confirm
}

func (e *ExternalMCPToolDefinition) GetConfirmPrompt() *string {
	if e == nil {
		return nil
	}
	return e.ConfirmPrompt
}

func (e *ExternalMCPToolDefinition) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *ExternalMCPToolDefinition) GetDeploymentExternalMcpID() string {
	if e == nil {
		return ""
	}
	return e.DeploymentExternalMcpID
}

func (e *ExternalMCPToolDefinition) GetDeploymentID() string {
	if e == nil {
		return ""
	}
	return e.DeploymentID
}

func (e *ExternalMCPToolDefinition) GetDescription() string {
	if e == nil {
		return ""
	}
	return e.Description
}

func (e *ExternalMCPToolDefinition) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ExternalMCPToolDefinition) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *ExternalMCPToolDefinition) GetOauthAuthorizationEndpoint() *string {
	if e == nil {
		return nil
	}
	return e.OauthAuthorizationEndpoint
}

func (e *ExternalMCPToolDefinition) GetOauthRegistrationEndpoint() *string {
	if e == nil {
		return nil
	}
	return e.OauthRegistrationEndpoint
}

func (e *ExternalMCPToolDefinition) GetOauthScopesSupported() []string {
	if e == nil {
		return nil
	}
	return e.OauthScopesSupported
}

func (e *ExternalMCPToolDefinition) GetOauthTokenEndpoint() *string {
	if e == nil {
		return nil
	}
	return e.OauthTokenEndpoint
}

func (e *ExternalMCPToolDefinition) GetOauthVersion() string {
	if e == nil {
		return ""
	}
	return e.OauthVersion
}

func (e *ExternalMCPToolDefinition) GetProjectID() string {
	if e == nil {
		return ""
	}
	return e.ProjectID
}

func (e *ExternalMCPToolDefinition) GetRegistryID() string {
	if e == nil {
		return ""
	}
	return e.RegistryID
}

func (e *ExternalMCPToolDefinition) GetRegistryServerName() string {
	if e == nil {
		return ""
	}
	return e.RegistryServerName
}

func (e *ExternalMCPToolDefinition) GetRegistrySpecifier() string {
	if e == nil {
		return ""
	}
	return e.RegistrySpecifier
}

func (e *ExternalMCPToolDefinition) GetRemoteURL() string {
	if e == nil {
		return ""
	}
	return e.RemoteURL
}

func (e *ExternalMCPToolDefinition) GetRequiresOauth() bool {
	if e == nil {
		return false
	}
	return e.RequiresOauth
}

func (e *ExternalMCPToolDefinition) GetSchema() string {
	if e == nil {
		return ""
	}
	return e.Schema
}

func (e *ExternalMCPToolDefinition) GetSchemaVersion() *string {
	if e == nil {
		return nil
	}
	return e.SchemaVersion
}

func (e *ExternalMCPToolDefinition) GetSlug() string {
	if e == nil {
		return ""
	}
	return e.Slug
}

func (e *ExternalMCPToolDefinition) GetSummarizer() *string {
	if e == nil {
		return nil
	}
	return e.Summarizer
}

func (e *ExternalMCPToolDefinition) GetToolUrn() string {
	if e == nil {
		return ""
	}
	return e.ToolUrn
}

func (e *ExternalMCPToolDefinition) GetTransportType() TransportType {
	if e == nil {
		return TransportType("")
	}
	return e.TransportType
}

func (e *ExternalMCPToolDefinition) GetType() *string {
	if e == nil {
		return nil
	}
	return e.Type
}

func (e *ExternalMCPToolDefinition) GetUpdatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.UpdatedAt
}

func (e *ExternalMCPToolDefinition) GetVariation() *ToolVariation {
	if e == nil {
		return nil
	}
	return e.Variation
}
