// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"time"
)

// FunctionToolDefinition - A function tool
type FunctionToolDefinition struct {
	// Tool annotations providing behavioral hints about the tool
	Annotations *ToolAnnotations `json:"annotations,omitzero"`
	// The ID of the asset
	AssetID string `json:"asset_id"`
	// The original details of a tool
	Canonical *CanonicalToolAttributes `json:"canonical,omitzero"`
	// The canonical name of the tool. Will be the same as the name if there is no variation.
	CanonicalName string `json:"canonical_name"`
	// Confirmation mode for the tool
	Confirm *string `json:"confirm,omitzero"`
	// Prompt for the confirmation
	ConfirmPrompt *string `json:"confirm_prompt,omitzero"`
	// The creation date of the tool.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the deployment
	DeploymentID string `json:"deployment_id"`
	// Description of the tool
	Description string `json:"description"`
	// The ID of the function
	FunctionID string `json:"function_id"`
	// The ID of the tool
	ID string `json:"id"`
	// Meta tags for the tool
	Meta map[string]any `json:"meta,omitzero"`
	// The name of the tool
	Name string `json:"name"`
	// The ID of the project
	ProjectID string `json:"project_id"`
	// Runtime environment (e.g., nodejs:24, python:3.12)
	Runtime string `json:"runtime"`
	// JSON schema for the request
	Schema string `json:"schema"`
	// Version of the schema
	SchemaVersion *string `json:"schema_version,omitzero"`
	// Summarizer for the tool
	Summarizer *string `json:"summarizer,omitzero"`
	// The URN of this tool
	ToolUrn string `json:"tool_urn"`
	// The last update date of the tool.
	UpdatedAt time.Time `json:"updated_at"`
	// Variables configuration for the function
	Variables any            `json:"variables,omitzero"`
	Variation *ToolVariation `json:"variation,omitzero"`
}

func (f FunctionToolDefinition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionToolDefinition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionToolDefinition) GetAnnotations() *ToolAnnotations {
	if f == nil {
		return nil
	}
	return f.Annotations
}

func (f *FunctionToolDefinition) GetAssetID() string {
	if f == nil {
		return ""
	}
	return f.AssetID
}

func (f *FunctionToolDefinition) GetCanonical() *CanonicalToolAttributes {
	if f == nil {
		return nil
	}
	return f.Canonical
}

func (f *FunctionToolDefinition) GetCanonicalName() string {
	if f == nil {
		return ""
	}
	return f.CanonicalName
}

func (f *FunctionToolDefinition) GetConfirm() *string {
	if f == nil {
		return nil
	}
	return f.Confirm
}

func (f *FunctionToolDefinition) GetConfirmPrompt() *string {
	if f == nil {
		return nil
	}
	return f.ConfirmPrompt
}

func (f *FunctionToolDefinition) GetCreatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CreatedAt
}

func (f *FunctionToolDefinition) GetDeploymentID() string {
	if f == nil {
		return ""
	}
	return f.DeploymentID
}

func (f *FunctionToolDefinition) GetDescription() string {
	if f == nil {
		return ""
	}
	return f.Description
}

func (f *FunctionToolDefinition) GetFunctionID() string {
	if f == nil {
		return ""
	}
	return f.FunctionID
}

func (f *FunctionToolDefinition) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FunctionToolDefinition) GetMeta() map[string]any {
	if f == nil {
		return nil
	}
	return f.Meta
}

func (f *FunctionToolDefinition) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FunctionToolDefinition) GetProjectID() string {
	if f == nil {
		return ""
	}
	return f.ProjectID
}

func (f *FunctionToolDefinition) GetRuntime() string {
	if f == nil {
		return ""
	}
	return f.Runtime
}

func (f *FunctionToolDefinition) GetSchema() string {
	if f == nil {
		return ""
	}
	return f.Schema
}

func (f *FunctionToolDefinition) GetSchemaVersion() *string {
	if f == nil {
		return nil
	}
	return f.SchemaVersion
}

func (f *FunctionToolDefinition) GetSummarizer() *string {
	if f == nil {
		return nil
	}
	return f.Summarizer
}

func (f *FunctionToolDefinition) GetToolUrn() string {
	if f == nil {
		return ""
	}
	return f.ToolUrn
}

func (f *FunctionToolDefinition) GetUpdatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.UpdatedAt
}

func (f *FunctionToolDefinition) GetVariables() any {
	if f == nil {
		return nil
	}
	return f.Variables
}

func (f *FunctionToolDefinition) GetVariation() *ToolVariation {
	if f == nil {
		return nil
	}
	return f.Variation
}
