// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FunctionEnvironmentVariable struct {
	// Optional value of the function variable comes from a specific auth input
	AuthInputType *string `json:"auth_input_type,omitzero"`
	// Description of the function environment variable
	Description *string `json:"description,omitzero"`
	// The environment variables
	Name string `json:"name"`
}

func (f *FunctionEnvironmentVariable) GetAuthInputType() *string {
	if f == nil {
		return nil
	}
	return f.AuthInputType
}

func (f *FunctionEnvironmentVariable) GetDescription() *string {
	if f == nil {
		return nil
	}
	return f.Description
}

func (f *FunctionEnvironmentVariable) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}
