// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"time"
)

// FunctionResourceDefinition - A function resource
type FunctionResourceDefinition struct {
	// The creation date of the resource.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the deployment
	DeploymentID string `json:"deployment_id"`
	// Description of the resource
	Description string `json:"description"`
	// The ID of the function
	FunctionID string `json:"function_id"`
	// The ID of the resource
	ID string `json:"id"`
	// Meta tags for the tool
	Meta map[string]any `json:"meta,omitzero"`
	// Optional MIME type of the resource
	MimeType *string `json:"mime_type,omitzero"`
	// The name of the resource
	Name string `json:"name"`
	// The ID of the project
	ProjectID string `json:"project_id"`
	// The URN of this resource
	ResourceUrn string `json:"resource_urn"`
	// Runtime environment (e.g., nodejs:24, python:3.12)
	Runtime string `json:"runtime"`
	// Optional title for the resource
	Title *string `json:"title,omitzero"`
	// The last update date of the resource.
	UpdatedAt time.Time `json:"updated_at"`
	// The URI of the resource
	URI string `json:"uri"`
	// Variables configuration for the resource
	Variables any `json:"variables,omitzero"`
}

func (f FunctionResourceDefinition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionResourceDefinition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionResourceDefinition) GetCreatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CreatedAt
}

func (f *FunctionResourceDefinition) GetDeploymentID() string {
	if f == nil {
		return ""
	}
	return f.DeploymentID
}

func (f *FunctionResourceDefinition) GetDescription() string {
	if f == nil {
		return ""
	}
	return f.Description
}

func (f *FunctionResourceDefinition) GetFunctionID() string {
	if f == nil {
		return ""
	}
	return f.FunctionID
}

func (f *FunctionResourceDefinition) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FunctionResourceDefinition) GetMeta() map[string]any {
	if f == nil {
		return nil
	}
	return f.Meta
}

func (f *FunctionResourceDefinition) GetMimeType() *string {
	if f == nil {
		return nil
	}
	return f.MimeType
}

func (f *FunctionResourceDefinition) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FunctionResourceDefinition) GetProjectID() string {
	if f == nil {
		return ""
	}
	return f.ProjectID
}

func (f *FunctionResourceDefinition) GetResourceUrn() string {
	if f == nil {
		return ""
	}
	return f.ResourceUrn
}

func (f *FunctionResourceDefinition) GetRuntime() string {
	if f == nil {
		return ""
	}
	return f.Runtime
}

func (f *FunctionResourceDefinition) GetTitle() *string {
	if f == nil {
		return nil
	}
	return f.Title
}

func (f *FunctionResourceDefinition) GetUpdatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.UpdatedAt
}

func (f *FunctionResourceDefinition) GetURI() string {
	if f == nil {
		return ""
	}
	return f.URI
}

func (f *FunctionResourceDefinition) GetVariables() any {
	if f == nil {
		return nil
	}
	return f.Variables
}
