// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"time"
)

type GetDeploymentResult struct {
	// The ID of the deployment that this deployment was cloned from.
	ClonedFrom *string `json:"cloned_from,omitzero"`
	// The creation date of the deployment.
	CreatedAt time.Time `json:"created_at"`
	// The external ID to refer to the deployment. This can be a git commit hash for example.
	ExternalID *string `json:"external_id,omitzero"`
	// The number of tools in the deployment generated from external MCP servers.
	ExternalMcpToolCount int64 `json:"external_mcp_tool_count"`
	// The external MCP servers that were deployed.
	ExternalMcps []DeploymentExternalMCP `json:"external_mcps,omitzero"`
	// The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
	ExternalURL *string `json:"external_url,omitzero"`
	// The IDs, as returned from the assets upload service, to uploaded OpenAPI 3.x documents whose operations will become tool definitions.
	FunctionsAssets []DeploymentFunctions `json:"functions_assets,omitzero"`
	// The number of tools in the deployment generated from Functions.
	FunctionsToolCount int64 `json:"functions_tool_count"`
	// The github pull request that resulted in the deployment.
	GithubPr *string `json:"github_pr,omitzero"`
	// The github repository in the form of "owner/repo".
	GithubRepo *string `json:"github_repo,omitzero"`
	// The commit hash that triggered the deployment.
	GithubSha *string `json:"github_sha,omitzero"`
	// The ID to of the deployment.
	ID string `json:"id"`
	// A unique identifier that will mitigate against duplicate deployments.
	IdempotencyKey *string `json:"idempotency_key,omitzero"`
	// The IDs, as returned from the assets upload service, to uploaded OpenAPI 3.x documents whose operations will become tool definitions.
	Openapiv3Assets []OpenAPIv3DeploymentAsset `json:"openapiv3_assets"`
	// The number of tools in the deployment generated from OpenAPI documents.
	Openapiv3ToolCount int64 `json:"openapiv3_tool_count"`
	// The ID of the organization that the deployment belongs to.
	OrganizationID string `json:"organization_id"`
	// The packages that were deployed.
	Packages []DeploymentPackage `json:"packages"`
	// The ID of the project that the deployment belongs to.
	ProjectID string `json:"project_id"`
	// The status of the deployment.
	Status string `json:"status"`
	// The ID of the user that created the deployment.
	UserID string `json:"user_id"`
}

func (g GetDeploymentResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDeploymentResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetDeploymentResult) GetClonedFrom() *string {
	if g == nil {
		return nil
	}
	return g.ClonedFrom
}

func (g *GetDeploymentResult) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GetDeploymentResult) GetExternalID() *string {
	if g == nil {
		return nil
	}
	return g.ExternalID
}

func (g *GetDeploymentResult) GetExternalMcpToolCount() int64 {
	if g == nil {
		return 0
	}
	return g.ExternalMcpToolCount
}

func (g *GetDeploymentResult) GetExternalMcps() []DeploymentExternalMCP {
	if g == nil {
		return nil
	}
	return g.ExternalMcps
}

func (g *GetDeploymentResult) GetExternalURL() *string {
	if g == nil {
		return nil
	}
	return g.ExternalURL
}

func (g *GetDeploymentResult) GetFunctionsAssets() []DeploymentFunctions {
	if g == nil {
		return nil
	}
	return g.FunctionsAssets
}

func (g *GetDeploymentResult) GetFunctionsToolCount() int64 {
	if g == nil {
		return 0
	}
	return g.FunctionsToolCount
}

func (g *GetDeploymentResult) GetGithubPr() *string {
	if g == nil {
		return nil
	}
	return g.GithubPr
}

func (g *GetDeploymentResult) GetGithubRepo() *string {
	if g == nil {
		return nil
	}
	return g.GithubRepo
}

func (g *GetDeploymentResult) GetGithubSha() *string {
	if g == nil {
		return nil
	}
	return g.GithubSha
}

func (g *GetDeploymentResult) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeploymentResult) GetIdempotencyKey() *string {
	if g == nil {
		return nil
	}
	return g.IdempotencyKey
}

func (g *GetDeploymentResult) GetOpenapiv3Assets() []OpenAPIv3DeploymentAsset {
	if g == nil {
		return []OpenAPIv3DeploymentAsset{}
	}
	return g.Openapiv3Assets
}

func (g *GetDeploymentResult) GetOpenapiv3ToolCount() int64 {
	if g == nil {
		return 0
	}
	return g.Openapiv3ToolCount
}

func (g *GetDeploymentResult) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetDeploymentResult) GetPackages() []DeploymentPackage {
	if g == nil {
		return []DeploymentPackage{}
	}
	return g.Packages
}

func (g *GetDeploymentResult) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetDeploymentResult) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetDeploymentResult) GetUserID() string {
	if g == nil {
		return ""
	}
	return g.UserID
}
