// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
)

type GetLatestDeploymentResult struct {
	Deployment *Deployment `json:"deployment,omitzero"`
}

func (g GetLatestDeploymentResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetLatestDeploymentResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetLatestDeploymentResult) GetDeployment() *Deployment {
	if g == nil {
		return nil
	}
	return g.Deployment
}
