// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"time"
)

// HTTPToolDefinition - An HTTP tool
type HTTPToolDefinition struct {
	// Tool annotations providing behavioral hints about the tool
	Annotations *ToolAnnotations `json:"annotations,omitzero"`
	// The ID of the asset
	AssetID string `json:"asset_id"`
	// The original details of a tool
	Canonical *CanonicalToolAttributes `json:"canonical,omitzero"`
	// The canonical name of the tool. Will be the same as the name if there is no variation.
	CanonicalName string `json:"canonical_name"`
	// Confirmation mode for the tool
	Confirm *string `json:"confirm,omitzero"`
	// Prompt for the confirmation
	ConfirmPrompt *string `json:"confirm_prompt,omitzero"`
	// The creation date of the tool.
	CreatedAt time.Time `json:"created_at"`
	// The default server URL for the tool
	DefaultServerURL *string `json:"default_server_url,omitzero"`
	// The ID of the deployment
	DeploymentID string `json:"deployment_id"`
	// Description of the tool
	Description string `json:"description"`
	// HTTP method for the request
	HTTPMethod string `json:"http_method"`
	// The ID of the tool
	ID string `json:"id"`
	// The name of the tool
	Name string `json:"name"`
	// The ID of the OpenAPI v3 document
	Openapiv3DocumentID *string `json:"openapiv3_document_id,omitzero"`
	// OpenAPI v3 operation
	Openapiv3Operation *string `json:"openapiv3_operation,omitzero"`
	// The name of the source package
	PackageName *string `json:"package_name,omitzero"`
	// Path for the request
	Path string `json:"path"`
	// The ID of the project
	ProjectID string `json:"project_id"`
	// Response filter metadata for the tool
	ResponseFilter *ResponseFilter `json:"response_filter,omitzero"`
	// JSON schema for the request
	Schema string `json:"schema"`
	// Version of the schema
	SchemaVersion *string `json:"schema_version,omitzero"`
	// Security requirements for the underlying HTTP endpoint
	Security *string `json:"security,omitzero"`
	// Summarizer for the tool
	Summarizer *string `json:"summarizer,omitzero"`
	// Summary of the tool
	Summary string `json:"summary"`
	// The tags list for this http tool
	Tags []string `json:"tags"`
	// The URN of this tool
	ToolUrn string `json:"tool_urn"`
	// The last update date of the tool.
	UpdatedAt time.Time      `json:"updated_at"`
	Variation *ToolVariation `json:"variation,omitzero"`
}

func (h HTTPToolDefinition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HTTPToolDefinition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HTTPToolDefinition) GetAnnotations() *ToolAnnotations {
	if h == nil {
		return nil
	}
	return h.Annotations
}

func (h *HTTPToolDefinition) GetAssetID() string {
	if h == nil {
		return ""
	}
	return h.AssetID
}

func (h *HTTPToolDefinition) GetCanonical() *CanonicalToolAttributes {
	if h == nil {
		return nil
	}
	return h.Canonical
}

func (h *HTTPToolDefinition) GetCanonicalName() string {
	if h == nil {
		return ""
	}
	return h.CanonicalName
}

func (h *HTTPToolDefinition) GetConfirm() *string {
	if h == nil {
		return nil
	}
	return h.Confirm
}

func (h *HTTPToolDefinition) GetConfirmPrompt() *string {
	if h == nil {
		return nil
	}
	return h.ConfirmPrompt
}

func (h *HTTPToolDefinition) GetCreatedAt() time.Time {
	if h == nil {
		return time.Time{}
	}
	return h.CreatedAt
}

func (h *HTTPToolDefinition) GetDefaultServerURL() *string {
	if h == nil {
		return nil
	}
	return h.DefaultServerURL
}

func (h *HTTPToolDefinition) GetDeploymentID() string {
	if h == nil {
		return ""
	}
	return h.DeploymentID
}

func (h *HTTPToolDefinition) GetDescription() string {
	if h == nil {
		return ""
	}
	return h.Description
}

func (h *HTTPToolDefinition) GetHTTPMethod() string {
	if h == nil {
		return ""
	}
	return h.HTTPMethod
}

func (h *HTTPToolDefinition) GetID() string {
	if h == nil {
		return ""
	}
	return h.ID
}

func (h *HTTPToolDefinition) GetName() string {
	if h == nil {
		return ""
	}
	return h.Name
}

func (h *HTTPToolDefinition) GetOpenapiv3DocumentID() *string {
	if h == nil {
		return nil
	}
	return h.Openapiv3DocumentID
}

func (h *HTTPToolDefinition) GetOpenapiv3Operation() *string {
	if h == nil {
		return nil
	}
	return h.Openapiv3Operation
}

func (h *HTTPToolDefinition) GetPackageName() *string {
	if h == nil {
		return nil
	}
	return h.PackageName
}

func (h *HTTPToolDefinition) GetPath() string {
	if h == nil {
		return ""
	}
	return h.Path
}

func (h *HTTPToolDefinition) GetProjectID() string {
	if h == nil {
		return ""
	}
	return h.ProjectID
}

func (h *HTTPToolDefinition) GetResponseFilter() *ResponseFilter {
	if h == nil {
		return nil
	}
	return h.ResponseFilter
}

func (h *HTTPToolDefinition) GetSchema() string {
	if h == nil {
		return ""
	}
	return h.Schema
}

func (h *HTTPToolDefinition) GetSchemaVersion() *string {
	if h == nil {
		return nil
	}
	return h.SchemaVersion
}

func (h *HTTPToolDefinition) GetSecurity() *string {
	if h == nil {
		return nil
	}
	return h.Security
}

func (h *HTTPToolDefinition) GetSummarizer() *string {
	if h == nil {
		return nil
	}
	return h.Summarizer
}

func (h *HTTPToolDefinition) GetSummary() string {
	if h == nil {
		return ""
	}
	return h.Summary
}

func (h *HTTPToolDefinition) GetTags() []string {
	if h == nil {
		return []string{}
	}
	return h.Tags
}

func (h *HTTPToolDefinition) GetToolUrn() string {
	if h == nil {
		return ""
	}
	return h.ToolUrn
}

func (h *HTTPToolDefinition) GetUpdatedAt() time.Time {
	if h == nil {
		return time.Time{}
	}
	return h.UpdatedAt
}

func (h *HTTPToolDefinition) GetVariation() *ToolVariation {
	if h == nil {
		return nil
	}
	return h.Variation
}
