// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListToolsetsResult struct {
	// The list of toolsets
	Toolsets []ToolsetEntry `json:"toolsets"`
}

func (l *ListToolsetsResult) GetToolsets() []ToolsetEntry {
	if l == nil {
		return []ToolsetEntry{}
	}
	return l.Toolsets
}
