// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OAuthEnablementMetadata struct {
	// Count of security variables that are OAuth2 supported
	Oauth2SecurityCount int64 `json:"oauth2_security_count"`
}

func (o *OAuthEnablementMetadata) GetOauth2SecurityCount() int64 {
	if o == nil {
		return 0
	}
	return o.Oauth2SecurityCount
}
