// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"time"
)

// ProviderType - The type of OAuth provider
type ProviderType string

const (
	ProviderTypeCustom ProviderType = "custom"
	ProviderTypeGram   ProviderType = "gram"
)

func (e ProviderType) ToPointer() *ProviderType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProviderType) IsExact() bool {
	if e != nil {
		switch *e {
		case "custom", "gram":
			return true
		}
	}
	return false
}

type OAuthProxyProvider struct {
	// The authorization endpoint URL
	AuthorizationEndpoint string `json:"authorization_endpoint"`
	// When the OAuth proxy provider was created.
	CreatedAt time.Time `json:"created_at"`
	// A short url-friendly label that uniquely identifies a resource.
	EnvironmentSlug *string `json:"environment_slug,omitzero"`
	// The grant types supported by this provider
	GrantTypesSupported []string `json:"grant_types_supported,omitzero"`
	// The ID of the OAuth proxy provider
	ID string `json:"id"`
	// The type of OAuth provider
	ProviderType ProviderType `json:"provider_type"`
	// The OAuth scopes supported by this provider
	ScopesSupported []string `json:"scopes_supported,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
	// The token endpoint URL
	TokenEndpoint string `json:"token_endpoint"`
	// The token endpoint auth methods supported by this provider
	TokenEndpointAuthMethodsSupported []string `json:"token_endpoint_auth_methods_supported,omitzero"`
	// When the OAuth proxy provider was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (o OAuthProxyProvider) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OAuthProxyProvider) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OAuthProxyProvider) GetAuthorizationEndpoint() string {
	if o == nil {
		return ""
	}
	return o.AuthorizationEndpoint
}

func (o *OAuthProxyProvider) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OAuthProxyProvider) GetEnvironmentSlug() *string {
	if o == nil {
		return nil
	}
	return o.EnvironmentSlug
}

func (o *OAuthProxyProvider) GetGrantTypesSupported() []string {
	if o == nil {
		return nil
	}
	return o.GrantTypesSupported
}

func (o *OAuthProxyProvider) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OAuthProxyProvider) GetProviderType() ProviderType {
	if o == nil {
		return ProviderType("")
	}
	return o.ProviderType
}

func (o *OAuthProxyProvider) GetScopesSupported() []string {
	if o == nil {
		return nil
	}
	return o.ScopesSupported
}

func (o *OAuthProxyProvider) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *OAuthProxyProvider) GetTokenEndpoint() string {
	if o == nil {
		return ""
	}
	return o.TokenEndpoint
}

func (o *OAuthProxyProvider) GetTokenEndpointAuthMethodsSupported() []string {
	if o == nil {
		return nil
	}
	return o.TokenEndpointAuthMethodsSupported
}

func (o *OAuthProxyProvider) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
