// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"time"
)

type OAuthProxyServer struct {
	// The audience parameter to send to the upstream OAuth provider
	Audience *string `json:"audience,omitzero"`
	// When the OAuth proxy server was created.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the OAuth proxy server
	ID string `json:"id"`
	// The OAuth proxy providers for this server
	OauthProxyProviders []OAuthProxyProvider `json:"oauth_proxy_providers,omitzero"`
	// The project ID this OAuth proxy server belongs to
	ProjectID string `json:"project_id"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
	// When the OAuth proxy server was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (o OAuthProxyServer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OAuthProxyServer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OAuthProxyServer) GetAudience() *string {
	if o == nil {
		return nil
	}
	return o.Audience
}

func (o *OAuthProxyServer) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OAuthProxyServer) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OAuthProxyServer) GetOauthProxyProviders() []OAuthProxyProvider {
	if o == nil {
		return nil
	}
	return o.OauthProxyProviders
}

func (o *OAuthProxyServer) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *OAuthProxyServer) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *OAuthProxyServer) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
