// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OpenAPIv3DeploymentAsset struct {
	// The ID of the uploaded asset.
	AssetID string `json:"asset_id"`
	// The ID of the deployment asset.
	ID string `json:"id"`
	// The name to give the document as it will be displayed in UIs.
	Name string `json:"name"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
}

func (o *OpenAPIv3DeploymentAsset) GetAssetID() string {
	if o == nil {
		return ""
	}
	return o.AssetID
}

func (o *OpenAPIv3DeploymentAsset) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OpenAPIv3DeploymentAsset) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OpenAPIv3DeploymentAsset) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// #region class-body-openapiv3deploymentasset
// #endregion class-body-openapiv3deploymentasset
