// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"time"
)

// PlatformToolDefinition - A platform-owned tool served directly by the platform
type PlatformToolDefinition struct {
	// Tool annotations providing behavioral hints about the tool
	Annotations *ToolAnnotations `json:"annotations,omitzero"`
	// The original details of a tool
	Canonical *CanonicalToolAttributes `json:"canonical,omitzero"`
	// The canonical name of the tool. Will be the same as the name if there is no variation.
	CanonicalName string `json:"canonical_name"`
	// Confirmation mode for the tool
	Confirm *string `json:"confirm,omitzero"`
	// Prompt for the confirmation
	ConfirmPrompt *string `json:"confirm_prompt,omitzero"`
	// The creation date of the tool.
	CreatedAt time.Time `json:"created_at"`
	// Description of the tool
	Description string `json:"description"`
	// The ID of the tool
	ID string `json:"id"`
	// The name of the tool
	Name string `json:"name"`
	// Optional owning entity ID
	OwnerID *string `json:"owner_id,omitzero"`
	// The entity kind that owns this tool's lifecycle
	OwnerKind *string `json:"owner_kind,omitzero"`
	// The ID of the project
	ProjectID string `json:"project_id"`
	// JSON schema for the request
	Schema string `json:"schema"`
	// Version of the schema
	SchemaVersion *string `json:"schema_version,omitzero"`
	// The backing platform tool source (for example: logs)
	SourceSlug string `json:"source_slug"`
	// Summarizer for the tool
	Summarizer *string `json:"summarizer,omitzero"`
	// The URN of this tool
	ToolUrn string `json:"tool_urn"`
	// The last update date of the tool.
	UpdatedAt time.Time      `json:"updated_at"`
	Variation *ToolVariation `json:"variation,omitzero"`
}

func (p PlatformToolDefinition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformToolDefinition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformToolDefinition) GetAnnotations() *ToolAnnotations {
	if p == nil {
		return nil
	}
	return p.Annotations
}

func (p *PlatformToolDefinition) GetCanonical() *CanonicalToolAttributes {
	if p == nil {
		return nil
	}
	return p.Canonical
}

func (p *PlatformToolDefinition) GetCanonicalName() string {
	if p == nil {
		return ""
	}
	return p.CanonicalName
}

func (p *PlatformToolDefinition) GetConfirm() *string {
	if p == nil {
		return nil
	}
	return p.Confirm
}

func (p *PlatformToolDefinition) GetConfirmPrompt() *string {
	if p == nil {
		return nil
	}
	return p.ConfirmPrompt
}

func (p *PlatformToolDefinition) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PlatformToolDefinition) GetDescription() string {
	if p == nil {
		return ""
	}
	return p.Description
}

func (p *PlatformToolDefinition) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PlatformToolDefinition) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PlatformToolDefinition) GetOwnerID() *string {
	if p == nil {
		return nil
	}
	return p.OwnerID
}

func (p *PlatformToolDefinition) GetOwnerKind() *string {
	if p == nil {
		return nil
	}
	return p.OwnerKind
}

func (p *PlatformToolDefinition) GetProjectID() string {
	if p == nil {
		return ""
	}
	return p.ProjectID
}

func (p *PlatformToolDefinition) GetSchema() string {
	if p == nil {
		return ""
	}
	return p.Schema
}

func (p *PlatformToolDefinition) GetSchemaVersion() *string {
	if p == nil {
		return nil
	}
	return p.SchemaVersion
}

func (p *PlatformToolDefinition) GetSourceSlug() string {
	if p == nil {
		return ""
	}
	return p.SourceSlug
}

func (p *PlatformToolDefinition) GetSummarizer() *string {
	if p == nil {
		return nil
	}
	return p.Summarizer
}

func (p *PlatformToolDefinition) GetToolUrn() string {
	if p == nil {
		return ""
	}
	return p.ToolUrn
}

func (p *PlatformToolDefinition) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *PlatformToolDefinition) GetVariation() *ToolVariation {
	if p == nil {
		return nil
	}
	return p.Variation
}
