// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"time"
)

// Engine - The template engine
type Engine string

const (
	EngineMustache Engine = "mustache"
)

func (e Engine) ToPointer() *Engine {
	return &e
}
func (e *Engine) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mustache":
		*e = Engine(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Engine: %v", v)
	}
}

// PromptTemplateKind - The kind of prompt the template is used for
type PromptTemplateKind string

const (
	PromptTemplateKindPrompt          PromptTemplateKind = "prompt"
	PromptTemplateKindHigherOrderTool PromptTemplateKind = "higher_order_tool"
)

func (e PromptTemplateKind) ToPointer() *PromptTemplateKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PromptTemplateKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "prompt", "higher_order_tool":
			return true
		}
	}
	return false
}

// PromptTemplate - A prompt template
type PromptTemplate struct {
	// Tool annotations providing behavioral hints about the tool
	Annotations *ToolAnnotations `json:"annotations,omitzero"`
	// The original details of a tool
	Canonical *CanonicalToolAttributes `json:"canonical,omitzero"`
	// The canonical name of the tool. Will be the same as the name if there is no variation.
	CanonicalName string `json:"canonical_name"`
	// Confirmation mode for the tool
	Confirm *string `json:"confirm,omitzero"`
	// Prompt for the confirmation
	ConfirmPrompt *string `json:"confirm_prompt,omitzero"`
	// The creation date of the tool.
	CreatedAt time.Time `json:"created_at"`
	// Description of the tool
	Description string `json:"description"`
	// The template engine
	Engine Engine `json:"engine"`
	// The revision tree ID for the prompt template
	HistoryID string `json:"history_id"`
	// The ID of the tool
	ID string `json:"id"`
	// The kind of prompt the template is used for
	Kind PromptTemplateKind `json:"kind"`
	// The name of the tool
	Name string `json:"name"`
	// The previous version of the prompt template to use as predecessor
	PredecessorID *string `json:"predecessor_id,omitzero"`
	// The ID of the project
	ProjectID string `json:"project_id"`
	// The template content
	Prompt string `json:"prompt"`
	// JSON schema for the request
	Schema string `json:"schema"`
	// Version of the schema
	SchemaVersion *string `json:"schema_version,omitzero"`
	// Summarizer for the tool
	Summarizer *string `json:"summarizer,omitzero"`
	// The URN of this tool
	ToolUrn string `json:"tool_urn"`
	// The suggested tool URNS associated with the prompt template
	ToolUrnsHint []string `json:"tool_urns_hint,omitzero"`
	// The suggested tool names associated with the prompt template
	ToolsHint []string `json:"tools_hint"`
	// The last update date of the tool.
	UpdatedAt time.Time      `json:"updated_at"`
	Variation *ToolVariation `json:"variation,omitzero"`
}

func (p PromptTemplate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PromptTemplate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PromptTemplate) GetAnnotations() *ToolAnnotations {
	if p == nil {
		return nil
	}
	return p.Annotations
}

func (p *PromptTemplate) GetCanonical() *CanonicalToolAttributes {
	if p == nil {
		return nil
	}
	return p.Canonical
}

func (p *PromptTemplate) GetCanonicalName() string {
	if p == nil {
		return ""
	}
	return p.CanonicalName
}

func (p *PromptTemplate) GetConfirm() *string {
	if p == nil {
		return nil
	}
	return p.Confirm
}

func (p *PromptTemplate) GetConfirmPrompt() *string {
	if p == nil {
		return nil
	}
	return p.ConfirmPrompt
}

func (p *PromptTemplate) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PromptTemplate) GetDescription() string {
	if p == nil {
		return ""
	}
	return p.Description
}

func (p *PromptTemplate) GetEngine() Engine {
	if p == nil {
		return Engine("")
	}
	return p.Engine
}

func (p *PromptTemplate) GetHistoryID() string {
	if p == nil {
		return ""
	}
	return p.HistoryID
}

func (p *PromptTemplate) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PromptTemplate) GetKind() PromptTemplateKind {
	if p == nil {
		return PromptTemplateKind("")
	}
	return p.Kind
}

func (p *PromptTemplate) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PromptTemplate) GetPredecessorID() *string {
	if p == nil {
		return nil
	}
	return p.PredecessorID
}

func (p *PromptTemplate) GetProjectID() string {
	if p == nil {
		return ""
	}
	return p.ProjectID
}

func (p *PromptTemplate) GetPrompt() string {
	if p == nil {
		return ""
	}
	return p.Prompt
}

func (p *PromptTemplate) GetSchema() string {
	if p == nil {
		return ""
	}
	return p.Schema
}

func (p *PromptTemplate) GetSchemaVersion() *string {
	if p == nil {
		return nil
	}
	return p.SchemaVersion
}

func (p *PromptTemplate) GetSummarizer() *string {
	if p == nil {
		return nil
	}
	return p.Summarizer
}

func (p *PromptTemplate) GetToolUrn() string {
	if p == nil {
		return ""
	}
	return p.ToolUrn
}

func (p *PromptTemplate) GetToolUrnsHint() []string {
	if p == nil {
		return nil
	}
	return p.ToolUrnsHint
}

func (p *PromptTemplate) GetToolsHint() []string {
	if p == nil {
		return []string{}
	}
	return p.ToolsHint
}

func (p *PromptTemplate) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *PromptTemplate) GetVariation() *ToolVariation {
	if p == nil {
		return nil
	}
	return p.Variation
}
