// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PromptTemplateEntry struct {
	// The ID of the prompt template
	ID string `json:"id"`
	// The kind of the prompt template
	Kind *string `json:"kind,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	Name string `json:"name"`
}

func (p *PromptTemplateEntry) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PromptTemplateEntry) GetKind() *string {
	if p == nil {
		return nil
	}
	return p.Kind
}

func (p *PromptTemplateEntry) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}
