// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RedeployRequestBody struct {
	// The ID of the deployment to redeploy.
	DeploymentID string `json:"deployment_id"`
}

func (r *RedeployRequestBody) GetDeploymentID() string {
	if r == nil {
		return ""
	}
	return r.DeploymentID
}
