// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
)

type RedeployResult struct {
	Deployment *Deployment `json:"deployment,omitzero"`
}

func (r RedeployResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RedeployResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RedeployResult) GetDeployment() *Deployment {
	if r == nil {
		return nil
	}
	return r.Deployment
}
