// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
)

// Resource - A polymorphic resource - currently only function resources are supported
type Resource struct {
	// A function resource
	FunctionResourceDefinition *FunctionResourceDefinition `json:"function_resource_definition,omitzero"`
}

func (r Resource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Resource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Resource) GetFunctionResourceDefinition() *FunctionResourceDefinition {
	if r == nil {
		return nil
	}
	return r.FunctionResourceDefinition
}
