// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Type string

const (
	TypeFunction Type = "function"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "function":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type ResourceEntry struct {
	// The ID of the resource
	ID string `json:"id"`
	// The name of the resource
	Name string `json:"name"`
	// The URN of the resource
	ResourceUrn string `json:"resource_urn"`
	Type        Type   `json:"type"`
	// The uri of the resource
	URI string `json:"uri"`
}

func (r *ResourceEntry) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ResourceEntry) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *ResourceEntry) GetResourceUrn() string {
	if r == nil {
		return ""
	}
	return r.ResourceUrn
}

func (r *ResourceEntry) GetType() Type {
	if r == nil {
		return Type("")
	}
	return r.Type
}

func (r *ResourceEntry) GetURI() string {
	if r == nil {
		return ""
	}
	return r.URI
}
