// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ResponseFilter - Response filter metadata for the tool
type ResponseFilter struct {
	// Content types to filter for
	ContentTypes []string `json:"content_types"`
	// Status codes to filter for
	StatusCodes []string `json:"status_codes"`
	// Response filter type for the tool
	Type string `json:"type"`
}

func (r *ResponseFilter) GetContentTypes() []string {
	if r == nil {
		return []string{}
	}
	return r.ContentTypes
}

func (r *ResponseFilter) GetStatusCodes() []string {
	if r == nil {
		return []string{}
	}
	return r.StatusCodes
}

func (r *ResponseFilter) GetType() string {
	if r == nil {
		return ""
	}
	return r.Type
}
