// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Security struct {
	ApikeyHeaderGramKey          *string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Key"`
	ProjectSlugHeaderGramProject *string `security:"scheme,type=apiKey,subtype=header,composite,name=Gram-Project"`
}

func (s *Security) GetApikeyHeaderGramKey() *string {
	if s == nil {
		return nil
	}
	return s.ApikeyHeaderGramKey
}

func (s *Security) GetProjectSlugHeaderGramProject() *string {
	if s == nil {
		return nil
	}
	return s.ProjectSlugHeaderGramProject
}
