// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
)

type SecurityVariable struct {
	// The bearer format
	BearerFormat *string `json:"bearer_format,omitzero"`
	// User-friendly display name for the security variable (defaults to name if not set)
	DisplayName *string `json:"display_name,omitzero"`
	// The environment variables
	EnvVariables []string `json:"env_variables"`
	// The unique identifier of the security variable
	ID string `json:"id"`
	// Where the security token is placed
	InPlacement string `json:"in_placement"`
	// The name of the security scheme (actual header/parameter name)
	Name string `json:"name"`
	// The OAuth flows
	OauthFlows []byte `json:"oauth_flows,omitzero"`
	// The OAuth types
	OauthTypes []string `json:"oauth_types,omitzero"`
	// The security scheme
	Scheme string `json:"scheme"`
	// The type of security
	Type *string `json:"type,omitzero"`
}

func (s SecurityVariable) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SecurityVariable) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SecurityVariable) GetBearerFormat() *string {
	if s == nil {
		return nil
	}
	return s.BearerFormat
}

func (s *SecurityVariable) GetDisplayName() *string {
	if s == nil {
		return nil
	}
	return s.DisplayName
}

func (s *SecurityVariable) GetEnvVariables() []string {
	if s == nil {
		return []string{}
	}
	return s.EnvVariables
}

func (s *SecurityVariable) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SecurityVariable) GetInPlacement() string {
	if s == nil {
		return ""
	}
	return s.InPlacement
}

func (s *SecurityVariable) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SecurityVariable) GetOauthFlows() []byte {
	if s == nil {
		return nil
	}
	return s.OauthFlows
}

func (s *SecurityVariable) GetOauthTypes() []string {
	if s == nil {
		return nil
	}
	return s.OauthTypes
}

func (s *SecurityVariable) GetScheme() string {
	if s == nil {
		return ""
	}
	return s.Scheme
}

func (s *SecurityVariable) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}
