// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ServerVariable struct {
	// Description of the server variable
	Description string `json:"description"`
	// The environment variables
	EnvVariables []string `json:"env_variables"`
}

func (s *ServerVariable) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *ServerVariable) GetEnvVariables() []string {
	if s == nil {
		return []string{}
	}
	return s.EnvVariables
}
