// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
	"time"
)

type Toolset struct {
	// The account type of the organization
	AccountType string `json:"account_type"`
	// When the toolset was created.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the custom domain to use for the toolset
	CustomDomainID *string `json:"custom_domain_id,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	DefaultEnvironmentSlug *string `json:"default_environment_slug,omitzero"`
	// Description of the toolset
	Description *string `json:"description,omitzero"`
	// The external MCP header definitions that are relevant to the toolset
	ExternalMcpHeaderDefinitions []ExternalMCPHeaderDefinition `json:"external_mcp_header_definitions,omitzero"`
	ExternalOauthServer          *ExternalOAuthServer          `json:"external_oauth_server,omitzero"`
	// The function environment variables that are relevant to the toolset
	FunctionEnvironmentVariables []FunctionEnvironmentVariable `json:"function_environment_variables,omitzero"`
	// The ID of the toolset
	ID string `json:"id"`
	// Whether the toolset is enabled for MCP
	McpEnabled *bool `json:"mcp_enabled,omitzero"`
	// Whether the toolset is public in MCP
	McpIsPublic *bool `json:"mcp_is_public,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	McpSlug *string `json:"mcp_slug,omitzero"`
	// The name of the toolset
	Name                    string                  `json:"name"`
	OauthEnablementMetadata OAuthEnablementMetadata `json:"oauth_enablement_metadata"`
	OauthProxyServer        *OAuthProxyServer       `json:"oauth_proxy_server,omitzero"`
	// The organization ID this toolset belongs to
	OrganizationID string         `json:"organization_id"`
	Origin         *ToolsetOrigin `json:"origin,omitzero"`
	// The project ID this toolset belongs to
	ProjectID string `json:"project_id"`
	// The prompt templates in this toolset -- Note: these are actual prompts, as in MCP prompts
	PromptTemplates []PromptTemplate `json:"prompt_templates"`
	// The resource URNs in this toolset
	ResourceUrns []string `json:"resource_urns"`
	// The resources in this toolset
	Resources []Resource `json:"resources"`
	// The security variables that are relevant to the toolset
	SecurityVariables []SecurityVariable `json:"security_variables,omitzero"`
	// The server variables that are relevant to the toolset
	ServerVariables []ServerVariable `json:"server_variables,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
	// The mode to use for tool selection
	ToolSelectionMode string `json:"tool_selection_mode"`
	// The tool URNs in this toolset
	ToolUrns []string `json:"tool_urns"`
	// The tools in this toolset
	Tools []Tool `json:"tools"`
	// The version of the toolset (will be 0 if none exists)
	ToolsetVersion int64 `json:"toolset_version"`
	// When the toolset was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (t Toolset) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Toolset) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Toolset) GetAccountType() string {
	if t == nil {
		return ""
	}
	return t.AccountType
}

func (t *Toolset) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *Toolset) GetCustomDomainID() *string {
	if t == nil {
		return nil
	}
	return t.CustomDomainID
}

func (t *Toolset) GetDefaultEnvironmentSlug() *string {
	if t == nil {
		return nil
	}
	return t.DefaultEnvironmentSlug
}

func (t *Toolset) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *Toolset) GetExternalMcpHeaderDefinitions() []ExternalMCPHeaderDefinition {
	if t == nil {
		return nil
	}
	return t.ExternalMcpHeaderDefinitions
}

func (t *Toolset) GetExternalOauthServer() *ExternalOAuthServer {
	if t == nil {
		return nil
	}
	return t.ExternalOauthServer
}

func (t *Toolset) GetFunctionEnvironmentVariables() []FunctionEnvironmentVariable {
	if t == nil {
		return nil
	}
	return t.FunctionEnvironmentVariables
}

func (t *Toolset) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Toolset) GetMcpEnabled() *bool {
	if t == nil {
		return nil
	}
	return t.McpEnabled
}

func (t *Toolset) GetMcpIsPublic() *bool {
	if t == nil {
		return nil
	}
	return t.McpIsPublic
}

func (t *Toolset) GetMcpSlug() *string {
	if t == nil {
		return nil
	}
	return t.McpSlug
}

func (t *Toolset) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *Toolset) GetOauthEnablementMetadata() OAuthEnablementMetadata {
	if t == nil {
		return OAuthEnablementMetadata{}
	}
	return t.OauthEnablementMetadata
}

func (t *Toolset) GetOauthProxyServer() *OAuthProxyServer {
	if t == nil {
		return nil
	}
	return t.OauthProxyServer
}

func (t *Toolset) GetOrganizationID() string {
	if t == nil {
		return ""
	}
	return t.OrganizationID
}

func (t *Toolset) GetOrigin() *ToolsetOrigin {
	if t == nil {
		return nil
	}
	return t.Origin
}

func (t *Toolset) GetProjectID() string {
	if t == nil {
		return ""
	}
	return t.ProjectID
}

func (t *Toolset) GetPromptTemplates() []PromptTemplate {
	if t == nil {
		return []PromptTemplate{}
	}
	return t.PromptTemplates
}

func (t *Toolset) GetResourceUrns() []string {
	if t == nil {
		return []string{}
	}
	return t.ResourceUrns
}

func (t *Toolset) GetResources() []Resource {
	if t == nil {
		return []Resource{}
	}
	return t.Resources
}

func (t *Toolset) GetSecurityVariables() []SecurityVariable {
	if t == nil {
		return nil
	}
	return t.SecurityVariables
}

func (t *Toolset) GetServerVariables() []ServerVariable {
	if t == nil {
		return nil
	}
	return t.ServerVariables
}

func (t *Toolset) GetSlug() string {
	if t == nil {
		return ""
	}
	return t.Slug
}

func (t *Toolset) GetToolSelectionMode() string {
	if t == nil {
		return ""
	}
	return t.ToolSelectionMode
}

func (t *Toolset) GetToolUrns() []string {
	if t == nil {
		return []string{}
	}
	return t.ToolUrns
}

func (t *Toolset) GetTools() []Tool {
	if t == nil {
		return []Tool{}
	}
	return t.Tools
}

func (t *Toolset) GetToolsetVersion() int64 {
	if t == nil {
		return 0
	}
	return t.ToolsetVersion
}

func (t *Toolset) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}
