// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ToolVariation struct {
	// The confirmation mode for the tool variation
	Confirm *string `json:"confirm,omitzero"`
	// The confirmation prompt for the tool variation
	ConfirmPrompt *string `json:"confirm_prompt,omitzero"`
	// The creation date of the tool variation
	CreatedAt string `json:"created_at"`
	// The description of the tool variation
	Description *string `json:"description,omitzero"`
	// Override: if true, the tool may perform destructive updates
	DestructiveHint *bool `json:"destructive_hint,omitzero"`
	// The ID of the tool variation group
	GroupID string `json:"group_id"`
	// The ID of the tool variation
	ID string `json:"id"`
	// Override: if true, repeated calls have no additional effect
	IdempotentHint *bool `json:"idempotent_hint,omitzero"`
	// The name of the tool variation
	Name *string `json:"name,omitzero"`
	// Override: if true, the tool interacts with external entities
	OpenWorldHint *bool `json:"open_world_hint,omitzero"`
	// Override: if true, the tool does not modify its environment
	ReadOnlyHint *bool `json:"read_only_hint,omitzero"`
	// The name of the source tool
	SrcToolName string `json:"src_tool_name"`
	// The URN of the source tool
	SrcToolUrn string `json:"src_tool_urn"`
	// The summarizer of the tool variation
	Summarizer *string `json:"summarizer,omitzero"`
	// Display name override for the tool
	Title *string `json:"title,omitzero"`
	// The last update date of the tool variation
	UpdatedAt string `json:"updated_at"`
}

func (t *ToolVariation) GetConfirm() *string {
	if t == nil {
		return nil
	}
	return t.Confirm
}

func (t *ToolVariation) GetConfirmPrompt() *string {
	if t == nil {
		return nil
	}
	return t.ConfirmPrompt
}

func (t *ToolVariation) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *ToolVariation) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *ToolVariation) GetDestructiveHint() *bool {
	if t == nil {
		return nil
	}
	return t.DestructiveHint
}

func (t *ToolVariation) GetGroupID() string {
	if t == nil {
		return ""
	}
	return t.GroupID
}

func (t *ToolVariation) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *ToolVariation) GetIdempotentHint() *bool {
	if t == nil {
		return nil
	}
	return t.IdempotentHint
}

func (t *ToolVariation) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *ToolVariation) GetOpenWorldHint() *bool {
	if t == nil {
		return nil
	}
	return t.OpenWorldHint
}

func (t *ToolVariation) GetReadOnlyHint() *bool {
	if t == nil {
		return nil
	}
	return t.ReadOnlyHint
}

func (t *ToolVariation) GetSrcToolName() string {
	if t == nil {
		return ""
	}
	return t.SrcToolName
}

func (t *ToolVariation) GetSrcToolUrn() string {
	if t == nil {
		return ""
	}
	return t.SrcToolUrn
}

func (t *ToolVariation) GetSummarizer() *string {
	if t == nil {
		return nil
	}
	return t.Summarizer
}

func (t *ToolVariation) GetTitle() *string {
	if t == nil {
		return nil
	}
	return t.Title
}

func (t *ToolVariation) GetUpdatedAt() string {
	if t == nil {
		return ""
	}
	return t.UpdatedAt
}
