// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ToolAnnotations - Tool annotations providing behavioral hints about the tool
type ToolAnnotations struct {
	// If true, the tool may perform destructive updates (only meaningful when read_only_hint is false)
	DestructiveHint *bool `json:"destructive_hint,omitzero"`
	// If true, repeated calls with same arguments have no additional effect (only meaningful when read_only_hint is false)
	IdempotentHint *bool `json:"idempotent_hint,omitzero"`
	// If true, the tool interacts with external entities beyond its local environment
	OpenWorldHint *bool `json:"open_world_hint,omitzero"`
	// If true, the tool does not modify its environment
	ReadOnlyHint *bool `json:"read_only_hint,omitzero"`
	// Human-readable display name for the tool
	Title *string `json:"title,omitzero"`
}

func (t *ToolAnnotations) GetDestructiveHint() *bool {
	if t == nil {
		return nil
	}
	return t.DestructiveHint
}

func (t *ToolAnnotations) GetIdempotentHint() *bool {
	if t == nil {
		return nil
	}
	return t.IdempotentHint
}

func (t *ToolAnnotations) GetOpenWorldHint() *bool {
	if t == nil {
		return nil
	}
	return t.OpenWorldHint
}

func (t *ToolAnnotations) GetReadOnlyHint() *bool {
	if t == nil {
		return nil
	}
	return t.ReadOnlyHint
}

func (t *ToolAnnotations) GetTitle() *string {
	if t == nil {
		return nil
	}
	return t.Title
}
