// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/cli/go/sdk/pkg/utils"
)

// Tool - A polymorphic tool - can be an HTTP tool, function tool, prompt template, or external MCP proxy
type Tool struct {
	// A proxy tool that references an external MCP server
	ExternalMcpToolDefinition *ExternalMCPToolDefinition `json:"external_mcp_tool_definition,omitzero"`
	// A function tool
	FunctionToolDefinition *FunctionToolDefinition `json:"function_tool_definition,omitzero"`
	// An HTTP tool
	HTTPToolDefinition *HTTPToolDefinition `json:"http_tool_definition,omitzero"`
	// A platform-owned tool served directly by the platform
	PlatformToolDefinition *PlatformToolDefinition `json:"platform_tool_definition,omitzero"`
	// A prompt template
	PromptTemplate *PromptTemplate `json:"prompt_template,omitzero"`
}

func (t Tool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Tool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Tool) GetExternalMcpToolDefinition() *ExternalMCPToolDefinition {
	if t == nil {
		return nil
	}
	return t.ExternalMcpToolDefinition
}

func (t *Tool) GetFunctionToolDefinition() *FunctionToolDefinition {
	if t == nil {
		return nil
	}
	return t.FunctionToolDefinition
}

func (t *Tool) GetHTTPToolDefinition() *HTTPToolDefinition {
	if t == nil {
		return nil
	}
	return t.HTTPToolDefinition
}

func (t *Tool) GetPlatformToolDefinition() *PlatformToolDefinition {
	if t == nil {
		return nil
	}
	return t.PlatformToolDefinition
}

func (t *Tool) GetPromptTemplate() *PromptTemplate {
	if t == nil {
		return nil
	}
	return t.PromptTemplate
}
