// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
)

type ToolEntryType string

const (
	ToolEntryTypeHTTP        ToolEntryType = "http"
	ToolEntryTypePrompt      ToolEntryType = "prompt"
	ToolEntryTypeFunction    ToolEntryType = "function"
	ToolEntryTypePlatform    ToolEntryType = "platform"
	ToolEntryTypeExternalmcp ToolEntryType = "externalmcp"
)

func (e ToolEntryType) ToPointer() *ToolEntryType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ToolEntryType) IsExact() bool {
	if e != nil {
		switch *e {
		case "http", "prompt", "function", "platform", "externalmcp":
			return true
		}
	}
	return false
}

type ToolEntry struct {
	// Tool annotations providing behavioral hints about the tool
	Annotations *ToolAnnotations `json:"annotations,omitzero"`
	// HTTP method for HTTP tools (GET, POST, PUT, PATCH, DELETE)
	HTTPMethod *string `json:"http_method,omitzero"`
	// The ID of the tool
	ID string `json:"id"`
	// The name of the tool
	Name string `json:"name"`
	// The URN of the tool
	ToolUrn string        `json:"tool_urn"`
	Type    ToolEntryType `json:"type"`
}

func (t ToolEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ToolEntry) GetAnnotations() *ToolAnnotations {
	if t == nil {
		return nil
	}
	return t.Annotations
}

func (t *ToolEntry) GetHTTPMethod() *string {
	if t == nil {
		return nil
	}
	return t.HTTPMethod
}

func (t *ToolEntry) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *ToolEntry) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *ToolEntry) GetToolUrn() string {
	if t == nil {
		return ""
	}
	return t.ToolUrn
}

func (t *ToolEntry) GetType() ToolEntryType {
	if t == nil {
		return ToolEntryType("")
	}
	return t.Type
}
