// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ToolsetOrigin struct {
	// The globally unique registry specifier this toolset originated from
	RegistrySpecifier string `json:"registry_specifier"`
}

func (t *ToolsetOrigin) GetRegistrySpecifier() string {
	if t == nil {
		return ""
	}
	return t.RegistrySpecifier
}
