// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/gf/go/sdk/pkg/utils"
	"time"
)

type ToolsetEntry struct {
	// When the toolset was created.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the custom domain to use for the toolset
	CustomDomainID *string `json:"custom_domain_id,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	DefaultEnvironmentSlug *string `json:"default_environment_slug,omitzero"`
	// Description of the toolset
	Description *string `json:"description,omitzero"`
	// The external MCP header definitions that are relevant to the toolset
	ExternalMcpHeaderDefinitions []ExternalMCPHeaderDefinition `json:"external_mcp_header_definitions,omitzero"`
	// The function environment variables that are relevant to the toolset
	FunctionEnvironmentVariables []FunctionEnvironmentVariable `json:"function_environment_variables,omitzero"`
	// The ID of the toolset
	ID string `json:"id"`
	// Whether the toolset is enabled for MCP
	McpEnabled *bool `json:"mcp_enabled,omitzero"`
	// Whether the toolset is public in MCP
	McpIsPublic *bool `json:"mcp_is_public,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	McpSlug *string `json:"mcp_slug,omitzero"`
	// The name of the toolset
	Name string `json:"name"`
	// The organization ID this toolset belongs to
	OrganizationID string         `json:"organization_id"`
	Origin         *ToolsetOrigin `json:"origin,omitzero"`
	// The project ID this toolset belongs to
	ProjectID string `json:"project_id"`
	// The prompt templates in this toolset -- Note: these are actual prompts, as in MCP prompts
	PromptTemplates []PromptTemplateEntry `json:"prompt_templates"`
	// The resource URNs in this toolset
	ResourceUrns []string `json:"resource_urns"`
	// The resources in this toolset
	Resources []ResourceEntry `json:"resources"`
	// The security variables that are relevant to the toolset
	SecurityVariables []SecurityVariable `json:"security_variables,omitzero"`
	// The server variables that are relevant to the toolset
	ServerVariables []ServerVariable `json:"server_variables,omitzero"`
	// A short url-friendly label that uniquely identifies a resource.
	Slug string `json:"slug"`
	// The mode to use for tool selection
	ToolSelectionMode string `json:"tool_selection_mode"`
	// The tool URNs in this toolset
	ToolUrns []string `json:"tool_urns"`
	// The tools in this toolset
	Tools []ToolEntry `json:"tools"`
	// When the toolset was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (t ToolsetEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolsetEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ToolsetEntry) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *ToolsetEntry) GetCustomDomainID() *string {
	if t == nil {
		return nil
	}
	return t.CustomDomainID
}

func (t *ToolsetEntry) GetDefaultEnvironmentSlug() *string {
	if t == nil {
		return nil
	}
	return t.DefaultEnvironmentSlug
}

func (t *ToolsetEntry) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *ToolsetEntry) GetExternalMcpHeaderDefinitions() []ExternalMCPHeaderDefinition {
	if t == nil {
		return nil
	}
	return t.ExternalMcpHeaderDefinitions
}

func (t *ToolsetEntry) GetFunctionEnvironmentVariables() []FunctionEnvironmentVariable {
	if t == nil {
		return nil
	}
	return t.FunctionEnvironmentVariables
}

func (t *ToolsetEntry) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *ToolsetEntry) GetMcpEnabled() *bool {
	if t == nil {
		return nil
	}
	return t.McpEnabled
}

func (t *ToolsetEntry) GetMcpIsPublic() *bool {
	if t == nil {
		return nil
	}
	return t.McpIsPublic
}

func (t *ToolsetEntry) GetMcpSlug() *string {
	if t == nil {
		return nil
	}
	return t.McpSlug
}

func (t *ToolsetEntry) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *ToolsetEntry) GetOrganizationID() string {
	if t == nil {
		return ""
	}
	return t.OrganizationID
}

func (t *ToolsetEntry) GetOrigin() *ToolsetOrigin {
	if t == nil {
		return nil
	}
	return t.Origin
}

func (t *ToolsetEntry) GetProjectID() string {
	if t == nil {
		return ""
	}
	return t.ProjectID
}

func (t *ToolsetEntry) GetPromptTemplates() []PromptTemplateEntry {
	if t == nil {
		return []PromptTemplateEntry{}
	}
	return t.PromptTemplates
}

func (t *ToolsetEntry) GetResourceUrns() []string {
	if t == nil {
		return []string{}
	}
	return t.ResourceUrns
}

func (t *ToolsetEntry) GetResources() []ResourceEntry {
	if t == nil {
		return []ResourceEntry{}
	}
	return t.Resources
}

func (t *ToolsetEntry) GetSecurityVariables() []SecurityVariable {
	if t == nil {
		return nil
	}
	return t.SecurityVariables
}

func (t *ToolsetEntry) GetServerVariables() []ServerVariable {
	if t == nil {
		return nil
	}
	return t.ServerVariables
}

func (t *ToolsetEntry) GetSlug() string {
	if t == nil {
		return ""
	}
	return t.Slug
}

func (t *ToolsetEntry) GetToolSelectionMode() string {
	if t == nil {
		return ""
	}
	return t.ToolSelectionMode
}

func (t *ToolsetEntry) GetToolUrns() []string {
	if t == nil {
		return []string{}
	}
	return t.ToolUrns
}

func (t *ToolsetEntry) GetTools() []ToolEntry {
	if t == nil {
		return []ToolEntry{}
	}
	return t.Tools
}

func (t *ToolsetEntry) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}
