// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UploadFunctionsResult struct {
	Asset Asset `json:"asset"`
}

func (u *UploadFunctionsResult) GetAsset() Asset {
	if u == nil {
		return Asset{}
	}
	return u.Asset
}
