// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UploadOpenAPIv3Result struct {
	Asset Asset `json:"asset"`
}

func (u *UploadOpenAPIv3Result) GetAsset() Asset {
	if u == nil {
		return Asset{}
	}
	return u.Asset
}

// #region class-body-uploadopenapiv3result
// #endregion class-body-uploadopenapiv3result
