// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ValidateKeyOrganization struct {
	// The ID of the organization
	ID string `json:"id"`
	// The name of the organization
	Name string `json:"name"`
	// The slug of the organization
	Slug string `json:"slug"`
}

func (v *ValidateKeyOrganization) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *ValidateKeyOrganization) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *ValidateKeyOrganization) GetSlug() string {
	if v == nil {
		return ""
	}
	return v.Slug
}
