// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ValidateKeyResult struct {
	Organization ValidateKeyOrganization `json:"organization"`
	// The projects accessible with this key
	Projects []ValidateKeyProject `json:"projects"`
	// List of permission scopes for this key
	Scopes []string `json:"scopes"`
}

func (v *ValidateKeyResult) GetOrganization() ValidateKeyOrganization {
	if v == nil {
		return ValidateKeyOrganization{}
	}
	return v.Organization
}

func (v *ValidateKeyResult) GetProjects() []ValidateKeyProject {
	if v == nil {
		return []ValidateKeyProject{}
	}
	return v.Projects
}

func (v *ValidateKeyResult) GetScopes() []string {
	if v == nil {
		return []string{}
	}
	return v.Scopes
}
