// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ValidateKeyProject struct {
	// The ID of the project
	ID string `json:"id"`
	// The name of the project
	Name string `json:"name"`
	// The slug of the project
	Slug string `json:"slug"`
}

func (v *ValidateKeyProject) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *ValidateKeyProject) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *ValidateKeyProject) GetSlug() string {
	if v == nil {
		return ""
	}
	return v.Slug
}
